// Auto-generated extension model for @swamp/gcp/doubleclickbidmanager/queries
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

import { z } from "zod";
import {
  createResource,
  deleteResource,
  getProjectId,
  isResourceNotFoundError,
  readResource,
} from "./_lib/gcp.ts";

const BASE_URL = "https://doubleclickbidmanager.googleapis.com/v2/";

const GET_CONFIG = {
  "id": "doubleclickbidmanager.queries.get",
  "path": "queries/{queryId}",
  "httpMethod": "GET",
  "parameterOrder": [
    "queryId",
  ],
  "parameters": {
    "queryId": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const INSERT_CONFIG = {
  "id": "doubleclickbidmanager.queries.create",
  "path": "queries",
  "httpMethod": "POST",
  "parameterOrder": [],
  "parameters": {},
} as const;

const DELETE_CONFIG = {
  "id": "doubleclickbidmanager.queries.delete",
  "path": "queries/{queryId}",
  "httpMethod": "DELETE",
  "parameterOrder": [
    "queryId",
  ],
  "parameters": {
    "queryId": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  name: z.string().describe(
    "Instance name for this resource (used as the unique identifier in the factory pattern)",
  ),
  metadata: z.object({
    dataRange: z.object({
      customEndDate: z.object({
        day: z.number().int().describe(
          "Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
        ).optional(),
        month: z.number().int().describe(
          "Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.",
        ).optional(),
        year: z.number().int().describe(
          "Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.",
        ).optional(),
      }).describe(
        "Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp",
      ).optional(),
      customStartDate: z.object({
        day: z.number().int().describe(
          "Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
        ).optional(),
        month: z.number().int().describe(
          "Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.",
        ).optional(),
        year: z.number().int().describe(
          "Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.",
        ).optional(),
      }).describe(
        "Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp",
      ).optional(),
      range: z.enum([
        "RANGE_UNSPECIFIED",
        "CUSTOM_DATES",
        "CURRENT_DAY",
        "PREVIOUS_DAY",
        "WEEK_TO_DATE",
        "MONTH_TO_DATE",
        "QUARTER_TO_DATE",
        "YEAR_TO_DATE",
        "PREVIOUS_WEEK",
        "PREVIOUS_MONTH",
        "PREVIOUS_QUARTER",
        "PREVIOUS_YEAR",
        "LAST_7_DAYS",
        "LAST_30_DAYS",
        "LAST_90_DAYS",
        "LAST_365_DAYS",
        "ALL_TIME",
        "LAST_14_DAYS",
        "LAST_60_DAYS",
      ]).describe(
        "The preset date range to be reported on. If `CUSTOM_DATES` is assigned to this field, fields custom_start_date and custom_end_date must be set to specify the custom date range.",
      ).optional(),
    }).describe("The date range to be reported on.").optional(),
    format: z.enum(["FORMAT_UNSPECIFIED", "CSV", "XLSX"]).describe(
      "The format of the report generated by the query.",
    ).optional(),
    sendNotification: z.boolean().describe(
      "Whether an email notification is sent to the query creator when a report generated by the query is ready. This value is `false` by default.",
    ).optional(),
    shareEmailAddress: z.array(z.string()).describe(
      "List of additional email addresses with which to share the query. If send_notification is `true`, these email addresses will receive a notification when a report generated by the query is ready. If these email addresses are connected to Display & Video 360 users, the query will be available to them in the Display & Video 360 interface.",
    ).optional(),
    title: z.string().describe(
      "The display name of the query. This value will be used in the file name of reports generated by the query.",
    ).optional(),
  }).describe("The metadata of the query.").optional(),
  params: z.object({
    filters: z.array(z.object({
      type: z.string().describe(
        "The type of value to filter by. Defined by a [Filter](/bid-manager/reference/rest/v2/filters-metrics#filters) value.",
      ).optional(),
      value: z.string().describe(
        "The identifying value to filter by, such as a relevant resource ID.",
      ).optional(),
    })).describe("Filters to limit the scope of reported data.").optional(),
    groupBys: z.array(z.string()).describe(
      "Dimensions by which to segment and group the data. Defined by [Filter](/bid-manager/reference/rest/v2/filters-metrics#filters) values.",
    ).optional(),
    metrics: z.array(z.string()).describe(
      "Metrics to define the data populating the report. Defined by [Metric](/bid-manager/reference/rest/v2/filters-metrics#metrics) values.",
    ).optional(),
    options: z.object({
      includeOnlyTargetedUserLists: z.boolean().describe(
        "Whether to include data for audience lists specifically targeted by filtered line items or insertion orders. Requires the use of `FILTER_INSERTION_ORDER` or `FILTER_LINE_ITEM` filters.",
      ).optional(),
    }).describe("Report parameter options.").optional(),
    type: z.enum([
      "REPORT_TYPE_UNSPECIFIED",
      "STANDARD",
      "INVENTORY_AVAILABILITY",
      "AUDIENCE_COMPOSITION",
      "FLOODLIGHT",
      "YOUTUBE",
      "GRP",
      "YOUTUBE_PROGRAMMATIC_GUARANTEED",
      "REACH",
      "UNIQUE_REACH_AUDIENCE",
      "FULL_PATH",
      "PATH_ATTRIBUTION",
    ]).describe(
      "The type of the report. The type of the report determines the dimesions, filters, and metrics that can be used.",
    ).optional(),
  }).describe("Parameters of a generated report.").optional(),
  schedule: z.object({
    endDate: z.object({
      day: z.number().int().describe(
        "Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
      ).optional(),
      month: z.number().int().describe(
        "Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.",
      ).optional(),
      year: z.number().int().describe(
        "Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.",
      ).optional(),
    }).describe(
      "Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp",
    ).optional(),
    frequency: z.enum([
      "FREQUENCY_UNSPECIFIED",
      "ONE_TIME",
      "DAILY",
      "WEEKLY",
      "SEMI_MONTHLY",
      "MONTHLY",
      "QUARTERLY",
      "YEARLY",
    ]).describe(
      "How frequently to run the query. If set to `ONE_TIME`, the query will only be run when queries.run is called.",
    ).optional(),
    nextRunTimezoneCode: z.string().describe(
      "The canonical code for the timezone the query schedule is based on. Scheduled runs are usually conducted in the morning of a given day. Defaults to `America/New_York`.",
    ).optional(),
    startDate: z.object({
      day: z.number().int().describe(
        "Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
      ).optional(),
      month: z.number().int().describe(
        "Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.",
      ).optional(),
      year: z.number().int().describe(
        "Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.",
      ).optional(),
    }).describe(
      "Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp",
    ).optional(),
  }).describe("Settings on when and how frequently to run a query.").optional(),
});

const StateSchema = z.object({
  metadata: z.object({
    dataRange: z.object({
      customEndDate: z.object({
        day: z.number(),
        month: z.number(),
        year: z.number(),
      }),
      customStartDate: z.object({
        day: z.number(),
        month: z.number(),
        year: z.number(),
      }),
      range: z.string(),
    }),
    format: z.string(),
    sendNotification: z.boolean(),
    shareEmailAddress: z.array(z.string()),
    title: z.string(),
  }).optional(),
  params: z.object({
    filters: z.array(z.object({
      type: z.string(),
      value: z.string(),
    })),
    groupBys: z.array(z.string()),
    metrics: z.array(z.string()),
    options: z.object({
      includeOnlyTargetedUserLists: z.boolean(),
    }),
    type: z.string(),
  }).optional(),
  queryId: z.string().optional(),
  schedule: z.object({
    endDate: z.object({
      day: z.number(),
      month: z.number(),
      year: z.number(),
    }),
    frequency: z.string(),
    nextRunTimezoneCode: z.string(),
    startDate: z.object({
      day: z.number(),
      month: z.number(),
      year: z.number(),
    }),
  }).optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  name: z.string().optional(),
  metadata: z.object({
    dataRange: z.object({
      customEndDate: z.object({
        day: z.number().int().describe(
          "Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
        ).optional(),
        month: z.number().int().describe(
          "Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.",
        ).optional(),
        year: z.number().int().describe(
          "Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.",
        ).optional(),
      }).describe(
        "Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp",
      ).optional(),
      customStartDate: z.object({
        day: z.number().int().describe(
          "Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
        ).optional(),
        month: z.number().int().describe(
          "Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.",
        ).optional(),
        year: z.number().int().describe(
          "Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.",
        ).optional(),
      }).describe(
        "Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp",
      ).optional(),
      range: z.enum([
        "RANGE_UNSPECIFIED",
        "CUSTOM_DATES",
        "CURRENT_DAY",
        "PREVIOUS_DAY",
        "WEEK_TO_DATE",
        "MONTH_TO_DATE",
        "QUARTER_TO_DATE",
        "YEAR_TO_DATE",
        "PREVIOUS_WEEK",
        "PREVIOUS_MONTH",
        "PREVIOUS_QUARTER",
        "PREVIOUS_YEAR",
        "LAST_7_DAYS",
        "LAST_30_DAYS",
        "LAST_90_DAYS",
        "LAST_365_DAYS",
        "ALL_TIME",
        "LAST_14_DAYS",
        "LAST_60_DAYS",
      ]).describe(
        "The preset date range to be reported on. If `CUSTOM_DATES` is assigned to this field, fields custom_start_date and custom_end_date must be set to specify the custom date range.",
      ).optional(),
    }).describe("The date range to be reported on.").optional(),
    format: z.enum(["FORMAT_UNSPECIFIED", "CSV", "XLSX"]).describe(
      "The format of the report generated by the query.",
    ).optional(),
    sendNotification: z.boolean().describe(
      "Whether an email notification is sent to the query creator when a report generated by the query is ready. This value is `false` by default.",
    ).optional(),
    shareEmailAddress: z.array(z.string()).describe(
      "List of additional email addresses with which to share the query. If send_notification is `true`, these email addresses will receive a notification when a report generated by the query is ready. If these email addresses are connected to Display & Video 360 users, the query will be available to them in the Display & Video 360 interface.",
    ).optional(),
    title: z.string().describe(
      "The display name of the query. This value will be used in the file name of reports generated by the query.",
    ).optional(),
  }).describe("The metadata of the query.").optional(),
  params: z.object({
    filters: z.array(z.object({
      type: z.string().describe(
        "The type of value to filter by. Defined by a [Filter](/bid-manager/reference/rest/v2/filters-metrics#filters) value.",
      ).optional(),
      value: z.string().describe(
        "The identifying value to filter by, such as a relevant resource ID.",
      ).optional(),
    })).describe("Filters to limit the scope of reported data.").optional(),
    groupBys: z.array(z.string()).describe(
      "Dimensions by which to segment and group the data. Defined by [Filter](/bid-manager/reference/rest/v2/filters-metrics#filters) values.",
    ).optional(),
    metrics: z.array(z.string()).describe(
      "Metrics to define the data populating the report. Defined by [Metric](/bid-manager/reference/rest/v2/filters-metrics#metrics) values.",
    ).optional(),
    options: z.object({
      includeOnlyTargetedUserLists: z.boolean().describe(
        "Whether to include data for audience lists specifically targeted by filtered line items or insertion orders. Requires the use of `FILTER_INSERTION_ORDER` or `FILTER_LINE_ITEM` filters.",
      ).optional(),
    }).describe("Report parameter options.").optional(),
    type: z.enum([
      "REPORT_TYPE_UNSPECIFIED",
      "STANDARD",
      "INVENTORY_AVAILABILITY",
      "AUDIENCE_COMPOSITION",
      "FLOODLIGHT",
      "YOUTUBE",
      "GRP",
      "YOUTUBE_PROGRAMMATIC_GUARANTEED",
      "REACH",
      "UNIQUE_REACH_AUDIENCE",
      "FULL_PATH",
      "PATH_ATTRIBUTION",
    ]).describe(
      "The type of the report. The type of the report determines the dimesions, filters, and metrics that can be used.",
    ).optional(),
  }).describe("Parameters of a generated report.").optional(),
  schedule: z.object({
    endDate: z.object({
      day: z.number().int().describe(
        "Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
      ).optional(),
      month: z.number().int().describe(
        "Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.",
      ).optional(),
      year: z.number().int().describe(
        "Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.",
      ).optional(),
    }).describe(
      "Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp",
    ).optional(),
    frequency: z.enum([
      "FREQUENCY_UNSPECIFIED",
      "ONE_TIME",
      "DAILY",
      "WEEKLY",
      "SEMI_MONTHLY",
      "MONTHLY",
      "QUARTERLY",
      "YEARLY",
    ]).describe(
      "How frequently to run the query. If set to `ONE_TIME`, the query will only be run when queries.run is called.",
    ).optional(),
    nextRunTimezoneCode: z.string().describe(
      "The canonical code for the timezone the query schedule is based on. Scheduled runs are usually conducted in the morning of a given day. Defaults to `America/New_York`.",
    ).optional(),
    startDate: z.object({
      day: z.number().int().describe(
        "Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
      ).optional(),
      month: z.number().int().describe(
        "Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.",
      ).optional(),
      year: z.number().int().describe(
        "Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.",
      ).optional(),
    }).describe(
      "Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp",
    ).optional(),
  }).describe("Settings on when and how frequently to run a query.").optional(),
});

export const model = {
  type: "@swamp/gcp/doubleclickbidmanager/queries",
  version: "2026.04.02.2",
  upgrades: [
    {
      toVersion: "2026.04.01.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.02.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],

  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description: "A single query used to generate a report.",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a queries",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const body: Record<string, unknown> = {};
        if (g["metadata"] !== undefined) body["metadata"] = g["metadata"];
        if (g["params"] !== undefined) body["params"] = g["params"];
        if (g["schedule"] !== undefined) body["schedule"] = g["schedule"];
        if (g["name"] !== undefined) params["queryId"] = String(g["name"]);
        const result = await createResource(
          BASE_URL,
          INSERT_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const instanceName = g.name?.toString() ?? "current";
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a queries",
      arguments: z.object({
        identifier: z.string().describe("The name of the queries"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const g = context.globalArgs;
        params["queryId"] = args.identifier;
        const result = await readResource(
          BASE_URL,
          GET_CONFIG,
          params,
        ) as StateData;
        const instanceName = g.name?.toString() ?? args.identifier;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete the queries",
      arguments: z.object({
        identifier: z.string().describe("The name of the queries"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        params["queryId"] = args.identifier;
        const { existed } = await deleteResource(
          BASE_URL,
          DELETE_CONFIG,
          params,
        );
        const instanceName = g.name?.toString() ?? args.identifier;
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync queries state from GCP",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { project: projectId };
          const identifier = existing.name?.toString() ?? g["name"]?.toString();
          if (!identifier) {
            throw new Error(
              "No identifier found in existing state or globalArgs",
            );
          }
          params["queryId"] = identifier;
          const result = await readResource(
            BASE_URL,
            GET_CONFIG,
            params,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
    run: {
      description: "run",
      arguments: z.object({
        dataRange: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          g.name?.toString() ?? "current",
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        params["queryId"] = existing["name"]?.toString() ??
          g["name"]?.toString() ?? "";
        const body: Record<string, unknown> = {};
        if (args["dataRange"] !== undefined) {
          body["dataRange"] = args["dataRange"];
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "doubleclickbidmanager.queries.run",
            "path": "queries/{queryId}:run",
            "httpMethod": "POST",
            "parameterOrder": ["queryId"],
            "parameters": {
              "queryId": { "location": "path", "required": true },
              "synchronous": { "location": "query" },
            },
          },
          params,
          body,
        );
        return { result };
      },
    },
  },
};
