// Auto-generated extension model for @swamp/gcp/reseller/subscriptions
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

import { z } from "zod";
import {
  createResource,
  deleteResource,
  getProjectId,
  isResourceNotFoundError,
  readResource,
} from "./_lib/gcp.ts";

const BASE_URL = "https://reseller.googleapis.com/";

const GET_CONFIG = {
  "id": "reseller.subscriptions.get",
  "path":
    "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}",
  "httpMethod": "GET",
  "parameterOrder": [
    "customerId",
    "subscriptionId",
  ],
  "parameters": {
    "customerId": {
      "location": "path",
      "required": true,
    },
    "subscriptionId": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const INSERT_CONFIG = {
  "id": "reseller.subscriptions.insert",
  "path": "apps/reseller/v1/customers/{customerId}/subscriptions",
  "httpMethod": "POST",
  "parameterOrder": [
    "customerId",
  ],
  "parameters": {
    "action": {
      "location": "query",
    },
    "customerAuthToken": {
      "location": "query",
    },
    "customerId": {
      "location": "path",
      "required": true,
    },
    "sourceSkuId": {
      "location": "query",
    },
  },
} as const;

const DELETE_CONFIG = {
  "id": "reseller.subscriptions.delete",
  "path":
    "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}",
  "httpMethod": "DELETE",
  "parameterOrder": [
    "customerId",
    "subscriptionId",
    "deletionType",
  ],
  "parameters": {
    "customerId": {
      "location": "path",
      "required": true,
    },
    "deletionType": {
      "location": "query",
      "required": true,
    },
    "subscriptionId": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  name: z.string().describe(
    "Instance name for this resource (used as the unique identifier in the factory pattern)",
  ),
  billingMethod: z.string().describe(
    "Read-only field that returns the current billing method for a subscription.",
  ).optional(),
  creationTime: z.string().describe(
    "The `creationTime` property is the date when subscription was created. It is in milliseconds using the Epoch format. See an example Epoch converter.",
  ).optional(),
  customerDomain: z.string().describe("Primary domain name of the customer")
    .optional(),
  customerId: z.string().describe(
    "This property will always be returned in a response as the unique identifier generated by Google. In a request, this property can be either the primary domain or the unique identifier generated by Google.",
  ).optional(),
  dealCode: z.string().describe(
    "Google-issued code (100 char max) for discounted pricing on subscription plans. Deal code must be included in `insert` requests in order to receive discounted rate. This property is optional, regular pricing applies if left empty.",
  ).optional(),
  plan: z.object({
    commitmentInterval: z.object({
      endTime: z.string().describe(
        "An annual commitment plan's interval's `endTime` in milliseconds using the UNIX Epoch format. See an example Epoch converter.",
      ).optional(),
      startTime: z.string().describe(
        "An annual commitment plan's interval's `startTime` in milliseconds using UNIX Epoch format. See an example Epoch converter.",
      ).optional(),
    }).describe(
      "In this version of the API, annual commitment plan's interval is one year. *Note: *When `billingMethod` value is `OFFLINE`, the subscription property object `plan.commitmentInterval` is omitted in all API responses.",
    ).optional(),
    isCommitmentPlan: z.boolean().describe(
      "The `isCommitmentPlan` property's boolean value identifies the plan as an annual commitment plan: - `true` — The subscription's plan is an annual commitment plan. - `false` — The plan is not an annual commitment plan.",
    ).optional(),
    planName: z.string().describe(
      "The `planName` property is required. This is the name of the subscription's plan. For more information about the Google payment plans, see the API concepts. Possible values are: - `ANNUAL_MONTHLY_PAY` — The annual commitment plan with monthly payments. *Caution: *`ANNUAL_MONTHLY_PAY` is returned as `ANNUAL` in all API responses. - `ANNUAL_YEARLY_PAY` — The annual commitment plan with yearly payments - `FLEXIBLE` — The flexible plan - `TRIAL` — The 30-day free trial plan. A subscription in trial will be suspended after the 30th free day if no payment plan is assigned. Calling `changePlan` will assign a payment plan to a trial but will not activate the plan. A trial will automatically begin its assigned payment plan after its 30th free day or immediately after calling `startPaidService`. - `FREE` — The free plan is exclusive to the Cloud Identity SKU and does not incur any billing.",
    ).optional(),
  }).describe(
    'The `plan` property is required. In this version of the API, the G Suite plans are the flexible plan, annual commitment plan, and the 30-day free trial plan. For more information about the API"s payment plans, see the API concepts.',
  ).optional(),
  purchaseOrderId: z.string().describe(
    "This is an optional property. This purchase order (PO) information is for resellers to use for their company tracking usage. If a `purchaseOrderId` value is given it appears in the API responses and shows up in the invoice. The property accepts up to 80 plain text characters.",
  ).optional(),
  renewalSettings: z.object({
    kind: z.string().describe(
      "Identifies the resource as a subscription renewal setting. Value: `subscriptions#renewalSettings`",
    ).optional(),
    renewalType: z.string().describe(
      "Renewal settings for the annual commitment plan. For more detailed information, see renewal options in the administrator help center. When renewing a subscription, the `renewalType` is a required property.",
    ).optional(),
  }).describe("JSON template for a subscription renewal settings.").optional(),
  resourceUiUrl: z.string().describe(
    "URL to customer's Subscriptions page in the Admin console. The read-only URL is generated by the API service. This is used if your client application requires the customer to complete a task using the Subscriptions page in the Admin console.",
  ).optional(),
  seats: z.object({
    kind: z.string().describe(
      "Identifies the resource as a subscription seat setting. Value: `subscriptions#seats`",
    ).optional(),
    licensedNumberOfSeats: z.number().int().describe(
      "Read-only field containing the current number of users that are assigned a license for the product defined in `skuId`. This field's value is equivalent to the numerical count of users returned by the Enterprise License Manager API method: [`listForProductAndSku`](https://developers.google.com/workspace/admin/licensing/v1/reference/licenseAssignments/listForProductAndSku).",
    ).optional(),
    maximumNumberOfSeats: z.number().int().describe(
      "This is a required property and is exclusive to subscriptions with `FLEXIBLE` or `TRIAL` plans. This property sets the maximum number of licensed users allowed on a subscription. This quantity can be increased up to the maximum limit defined in the reseller's contract. The minimum quantity is the current number of users in the customer account. *Note: *G Suite subscriptions automatically assign a license to every user.",
    ).optional(),
    numberOfSeats: z.number().int().describe(
      "This is a required property and is exclusive to subscriptions with `ANNUAL_MONTHLY_PAY` and `ANNUAL_YEARLY_PAY` plans. This property sets the maximum number of licenses assignable to users on a subscription. The reseller can add more licenses, but once set, the `numberOfSeats` cannot be reduced until renewal. The reseller is invoiced based on the `numberOfSeats` value regardless of how many of these user licenses are assigned. *Note: *Google Workspace subscriptions automatically assign a license to every user.",
    ).optional(),
  }).describe("JSON template for subscription seats.").optional(),
  skuId: z.string().describe(
    "A required property. The `skuId` is a unique system identifier for a product's SKU assigned to a customer in the subscription. For products and SKUs available in this version of the API, see Product and SKU IDs.",
  ).optional(),
  skuName: z.string().describe(
    "Read-only external display name for a product's SKU assigned to a customer in the subscription. SKU names are subject to change at Google's discretion. For products and SKUs available in this version of the API, see Product and SKU IDs.",
  ).optional(),
  status: z.string().describe("This is an optional property.").optional(),
  subscriptionId: z.string().describe(
    "The `subscriptionId` is the subscription identifier and is unique for each customer. This is a required property. Since a `subscriptionId` changes when a subscription is updated, we recommend not using this ID as a key for persistent data. Use the `subscriptionId` as described in retrieve all reseller subscriptions.",
  ).optional(),
  suspensionReasons: z.array(z.string()).describe(
    "Read-only field containing an enumerable of all the current suspension reasons for a subscription. It is possible for a subscription to have many concurrent, overlapping suspension reasons. A subscription's `STATUS` is `SUSPENDED` until all pending suspensions are removed. Possible options include: - `PENDING_TOS_ACCEPTANCE` - The customer has not logged in and accepted the G Suite Resold Terms of Services. - `RENEWAL_WITH_TYPE_CANCEL` - The customer's commitment ended and their service was cancelled at the end of their term. - `RESELLER_INITIATED` - A manual suspension invoked by a Reseller. - `TRIAL_ENDED` - The customer's trial expired without a plan selected. - `OTHER` - The customer is suspended for an internal Google reason (e.g. abuse or otherwise).",
  ).optional(),
  transferInfo: z.object({
    currentLegacySkuId: z.string().describe(
      "The `skuId` of the current resold subscription. This is populated only when the customer has a subscription with a legacy SKU and the subscription resource is populated with the `skuId` of the SKU recommended for the transfer.",
    ).optional(),
    minimumTransferableSeats: z.number().int().describe(
      "When inserting a subscription, this is the minimum number of seats listed in the transfer order for this product. For example, if the customer has 20 users, the reseller cannot place a transfer order of 15 seats. The minimum is 20 seats.",
    ).optional(),
    transferabilityExpirationTime: z.string().describe(
      "The time when transfer token or intent to transfer will expire. The time is in milliseconds using UNIX Epoch format.",
    ).optional(),
  }).describe(
    "Read-only transfer related information for the subscription. For more information, see retrieve transferable subscriptions for a customer.",
  ).optional(),
  trialSettings: z.object({
    isInTrial: z.boolean().describe(
      "Determines if a subscription's plan is in a 30-day free trial or not: - `true` — The plan is in trial. - `false` — The plan is not in trial.",
    ).optional(),
    trialEndTime: z.string().describe(
      "Date when the trial ends. The value is in milliseconds using the UNIX Epoch format. See an example Epoch converter.",
    ).optional(),
  }).describe(
    "The G Suite annual commitment and flexible payment plans can be in a 30-day free trial. For more information, see the API concepts.",
  ).optional(),
  action: z.string().describe(
    "The intented insert action. Advised to set this when the customer already has a subscription for a different SKU in the same product.",
  ).optional(),
  customerAuthToken: z.string().describe(
    "The `customerAuthToken` query string is required when creating a resold account that transfers a direct customer's subscription or transfers another reseller customer's subscription to your reseller management. This is a hexadecimal authentication token needed to complete the subscription transfer. For more information, see the administrator help center.",
  ).optional(),
  sourceSkuId: z.string().describe(
    "The sku_id of the existing subscription to be upgraded or downgraded. This is required when action is SWITCH.",
  ).optional(),
});

const StateSchema = z.object({
  billingMethod: z.string().optional(),
  creationTime: z.string().optional(),
  customerDomain: z.string().optional(),
  customerId: z.string().optional(),
  dealCode: z.string().optional(),
  kind: z.string().optional(),
  plan: z.object({
    commitmentInterval: z.object({
      endTime: z.string(),
      startTime: z.string(),
    }),
    isCommitmentPlan: z.boolean(),
    planName: z.string(),
  }).optional(),
  purchaseOrderId: z.string().optional(),
  renewalSettings: z.object({
    kind: z.string(),
    renewalType: z.string(),
  }).optional(),
  resourceUiUrl: z.string().optional(),
  seats: z.object({
    kind: z.string(),
    licensedNumberOfSeats: z.number(),
    maximumNumberOfSeats: z.number(),
    numberOfSeats: z.number(),
  }).optional(),
  skuId: z.string().optional(),
  skuName: z.string().optional(),
  status: z.string().optional(),
  subscriptionId: z.string().optional(),
  suspensionReasons: z.array(z.string()).optional(),
  transferInfo: z.object({
    currentLegacySkuId: z.string(),
    minimumTransferableSeats: z.number(),
    transferabilityExpirationTime: z.string(),
  }).optional(),
  trialSettings: z.object({
    isInTrial: z.boolean(),
    trialEndTime: z.string(),
  }).optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  name: z.string().optional(),
  billingMethod: z.string().describe(
    "Read-only field that returns the current billing method for a subscription.",
  ).optional(),
  creationTime: z.string().describe(
    "The `creationTime` property is the date when subscription was created. It is in milliseconds using the Epoch format. See an example Epoch converter.",
  ).optional(),
  customerDomain: z.string().describe("Primary domain name of the customer")
    .optional(),
  customerId: z.string().describe(
    "This property will always be returned in a response as the unique identifier generated by Google. In a request, this property can be either the primary domain or the unique identifier generated by Google.",
  ).optional(),
  dealCode: z.string().describe(
    "Google-issued code (100 char max) for discounted pricing on subscription plans. Deal code must be included in `insert` requests in order to receive discounted rate. This property is optional, regular pricing applies if left empty.",
  ).optional(),
  plan: z.object({
    commitmentInterval: z.object({
      endTime: z.string().describe(
        "An annual commitment plan's interval's `endTime` in milliseconds using the UNIX Epoch format. See an example Epoch converter.",
      ).optional(),
      startTime: z.string().describe(
        "An annual commitment plan's interval's `startTime` in milliseconds using UNIX Epoch format. See an example Epoch converter.",
      ).optional(),
    }).describe(
      "In this version of the API, annual commitment plan's interval is one year. *Note: *When `billingMethod` value is `OFFLINE`, the subscription property object `plan.commitmentInterval` is omitted in all API responses.",
    ).optional(),
    isCommitmentPlan: z.boolean().describe(
      "The `isCommitmentPlan` property's boolean value identifies the plan as an annual commitment plan: - `true` — The subscription's plan is an annual commitment plan. - `false` — The plan is not an annual commitment plan.",
    ).optional(),
    planName: z.string().describe(
      "The `planName` property is required. This is the name of the subscription's plan. For more information about the Google payment plans, see the API concepts. Possible values are: - `ANNUAL_MONTHLY_PAY` — The annual commitment plan with monthly payments. *Caution: *`ANNUAL_MONTHLY_PAY` is returned as `ANNUAL` in all API responses. - `ANNUAL_YEARLY_PAY` — The annual commitment plan with yearly payments - `FLEXIBLE` — The flexible plan - `TRIAL` — The 30-day free trial plan. A subscription in trial will be suspended after the 30th free day if no payment plan is assigned. Calling `changePlan` will assign a payment plan to a trial but will not activate the plan. A trial will automatically begin its assigned payment plan after its 30th free day or immediately after calling `startPaidService`. - `FREE` — The free plan is exclusive to the Cloud Identity SKU and does not incur any billing.",
    ).optional(),
  }).describe(
    'The `plan` property is required. In this version of the API, the G Suite plans are the flexible plan, annual commitment plan, and the 30-day free trial plan. For more information about the API"s payment plans, see the API concepts.',
  ).optional(),
  purchaseOrderId: z.string().describe(
    "This is an optional property. This purchase order (PO) information is for resellers to use for their company tracking usage. If a `purchaseOrderId` value is given it appears in the API responses and shows up in the invoice. The property accepts up to 80 plain text characters.",
  ).optional(),
  renewalSettings: z.object({
    kind: z.string().describe(
      "Identifies the resource as a subscription renewal setting. Value: `subscriptions#renewalSettings`",
    ).optional(),
    renewalType: z.string().describe(
      "Renewal settings for the annual commitment plan. For more detailed information, see renewal options in the administrator help center. When renewing a subscription, the `renewalType` is a required property.",
    ).optional(),
  }).describe("JSON template for a subscription renewal settings.").optional(),
  resourceUiUrl: z.string().describe(
    "URL to customer's Subscriptions page in the Admin console. The read-only URL is generated by the API service. This is used if your client application requires the customer to complete a task using the Subscriptions page in the Admin console.",
  ).optional(),
  seats: z.object({
    kind: z.string().describe(
      "Identifies the resource as a subscription seat setting. Value: `subscriptions#seats`",
    ).optional(),
    licensedNumberOfSeats: z.number().int().describe(
      "Read-only field containing the current number of users that are assigned a license for the product defined in `skuId`. This field's value is equivalent to the numerical count of users returned by the Enterprise License Manager API method: [`listForProductAndSku`](https://developers.google.com/workspace/admin/licensing/v1/reference/licenseAssignments/listForProductAndSku).",
    ).optional(),
    maximumNumberOfSeats: z.number().int().describe(
      "This is a required property and is exclusive to subscriptions with `FLEXIBLE` or `TRIAL` plans. This property sets the maximum number of licensed users allowed on a subscription. This quantity can be increased up to the maximum limit defined in the reseller's contract. The minimum quantity is the current number of users in the customer account. *Note: *G Suite subscriptions automatically assign a license to every user.",
    ).optional(),
    numberOfSeats: z.number().int().describe(
      "This is a required property and is exclusive to subscriptions with `ANNUAL_MONTHLY_PAY` and `ANNUAL_YEARLY_PAY` plans. This property sets the maximum number of licenses assignable to users on a subscription. The reseller can add more licenses, but once set, the `numberOfSeats` cannot be reduced until renewal. The reseller is invoiced based on the `numberOfSeats` value regardless of how many of these user licenses are assigned. *Note: *Google Workspace subscriptions automatically assign a license to every user.",
    ).optional(),
  }).describe("JSON template for subscription seats.").optional(),
  skuId: z.string().describe(
    "A required property. The `skuId` is a unique system identifier for a product's SKU assigned to a customer in the subscription. For products and SKUs available in this version of the API, see Product and SKU IDs.",
  ).optional(),
  skuName: z.string().describe(
    "Read-only external display name for a product's SKU assigned to a customer in the subscription. SKU names are subject to change at Google's discretion. For products and SKUs available in this version of the API, see Product and SKU IDs.",
  ).optional(),
  status: z.string().describe("This is an optional property.").optional(),
  subscriptionId: z.string().describe(
    "The `subscriptionId` is the subscription identifier and is unique for each customer. This is a required property. Since a `subscriptionId` changes when a subscription is updated, we recommend not using this ID as a key for persistent data. Use the `subscriptionId` as described in retrieve all reseller subscriptions.",
  ).optional(),
  suspensionReasons: z.array(z.string()).describe(
    "Read-only field containing an enumerable of all the current suspension reasons for a subscription. It is possible for a subscription to have many concurrent, overlapping suspension reasons. A subscription's `STATUS` is `SUSPENDED` until all pending suspensions are removed. Possible options include: - `PENDING_TOS_ACCEPTANCE` - The customer has not logged in and accepted the G Suite Resold Terms of Services. - `RENEWAL_WITH_TYPE_CANCEL` - The customer's commitment ended and their service was cancelled at the end of their term. - `RESELLER_INITIATED` - A manual suspension invoked by a Reseller. - `TRIAL_ENDED` - The customer's trial expired without a plan selected. - `OTHER` - The customer is suspended for an internal Google reason (e.g. abuse or otherwise).",
  ).optional(),
  transferInfo: z.object({
    currentLegacySkuId: z.string().describe(
      "The `skuId` of the current resold subscription. This is populated only when the customer has a subscription with a legacy SKU and the subscription resource is populated with the `skuId` of the SKU recommended for the transfer.",
    ).optional(),
    minimumTransferableSeats: z.number().int().describe(
      "When inserting a subscription, this is the minimum number of seats listed in the transfer order for this product. For example, if the customer has 20 users, the reseller cannot place a transfer order of 15 seats. The minimum is 20 seats.",
    ).optional(),
    transferabilityExpirationTime: z.string().describe(
      "The time when transfer token or intent to transfer will expire. The time is in milliseconds using UNIX Epoch format.",
    ).optional(),
  }).describe(
    "Read-only transfer related information for the subscription. For more information, see retrieve transferable subscriptions for a customer.",
  ).optional(),
  trialSettings: z.object({
    isInTrial: z.boolean().describe(
      "Determines if a subscription's plan is in a 30-day free trial or not: - `true` — The plan is in trial. - `false` — The plan is not in trial.",
    ).optional(),
    trialEndTime: z.string().describe(
      "Date when the trial ends. The value is in milliseconds using the UNIX Epoch format. See an example Epoch converter.",
    ).optional(),
  }).describe(
    "The G Suite annual commitment and flexible payment plans can be in a 30-day free trial. For more information, see the API concepts.",
  ).optional(),
  action: z.string().describe(
    "The intented insert action. Advised to set this when the customer already has a subscription for a different SKU in the same product.",
  ).optional(),
  customerAuthToken: z.string().describe(
    "The `customerAuthToken` query string is required when creating a resold account that transfers a direct customer's subscription or transfers another reseller customer's subscription to your reseller management. This is a hexadecimal authentication token needed to complete the subscription transfer. For more information, see the administrator help center.",
  ).optional(),
  sourceSkuId: z.string().describe(
    "The sku_id of the existing subscription to be upgraded or downgraded. This is required when action is SWITCH.",
  ).optional(),
});

export const model = {
  type: "@swamp/gcp/reseller/subscriptions",
  version: "2026.04.01.1",
  upgrades: [
    {
      toVersion: "2026.04.01.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description: "JSON template for a subscription.",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a subscriptions",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["customerId"] !== undefined) {
          params["customerId"] = String(g["customerId"]);
        }
        const body: Record<string, unknown> = {};
        if (g["billingMethod"] !== undefined) {
          body["billingMethod"] = g["billingMethod"];
        }
        if (g["creationTime"] !== undefined) {
          body["creationTime"] = g["creationTime"];
        }
        if (g["customerDomain"] !== undefined) {
          body["customerDomain"] = g["customerDomain"];
        }
        if (g["dealCode"] !== undefined) body["dealCode"] = g["dealCode"];
        if (g["plan"] !== undefined) body["plan"] = g["plan"];
        if (g["purchaseOrderId"] !== undefined) {
          body["purchaseOrderId"] = g["purchaseOrderId"];
        }
        if (g["renewalSettings"] !== undefined) {
          body["renewalSettings"] = g["renewalSettings"];
        }
        if (g["resourceUiUrl"] !== undefined) {
          body["resourceUiUrl"] = g["resourceUiUrl"];
        }
        if (g["seats"] !== undefined) body["seats"] = g["seats"];
        if (g["skuId"] !== undefined) body["skuId"] = g["skuId"];
        if (g["skuName"] !== undefined) body["skuName"] = g["skuName"];
        if (g["status"] !== undefined) body["status"] = g["status"];
        if (g["subscriptionId"] !== undefined) {
          body["subscriptionId"] = g["subscriptionId"];
        }
        if (g["suspensionReasons"] !== undefined) {
          body["suspensionReasons"] = g["suspensionReasons"];
        }
        if (g["transferInfo"] !== undefined) {
          body["transferInfo"] = g["transferInfo"];
        }
        if (g["trialSettings"] !== undefined) {
          body["trialSettings"] = g["trialSettings"];
        }
        if (g["action"] !== undefined) body["action"] = g["action"];
        if (g["customerAuthToken"] !== undefined) {
          body["customerAuthToken"] = g["customerAuthToken"];
        }
        if (g["sourceSkuId"] !== undefined) {
          body["sourceSkuId"] = g["sourceSkuId"];
        }
        if (g["name"] !== undefined) {
          params["subscriptionId"] = String(g["name"]);
        }
        const result = await createResource(
          BASE_URL,
          INSERT_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const instanceName = g.name?.toString() ?? "current";
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a subscriptions",
      arguments: z.object({
        identifier: z.string().describe("The name of the subscriptions"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const g = context.globalArgs;
        if (g["customerId"] !== undefined) {
          params["customerId"] = String(g["customerId"]);
        }
        params["subscriptionId"] = args.identifier;
        const result = await readResource(
          BASE_URL,
          GET_CONFIG,
          params,
        ) as StateData;
        const instanceName = g.name?.toString() ?? args.identifier;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete the subscriptions",
      arguments: z.object({
        identifier: z.string().describe("The name of the subscriptions"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["customerId"] !== undefined) {
          params["customerId"] = String(g["customerId"]);
        }
        if (g["subscriptionId"] !== undefined) {
          params["subscriptionId"] = String(g["subscriptionId"]);
        }
        params["deletionType"] = args.identifier;
        const { existed } = await deleteResource(
          BASE_URL,
          DELETE_CONFIG,
          params,
        );
        const instanceName = g.name?.toString() ?? args.identifier;
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync subscriptions state from GCP",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { project: projectId };
          if (g["customerId"] !== undefined) {
            params["customerId"] = String(g["customerId"]);
          } else if (existing["customerId"]) {
            params["customerId"] = String(existing["customerId"]);
          }
          const identifier = existing.name?.toString() ?? g["name"]?.toString();
          if (!identifier) {
            throw new Error(
              "No identifier found in existing state or globalArgs",
            );
          }
          params["subscriptionId"] = identifier;
          const result = await readResource(
            BASE_URL,
            GET_CONFIG,
            params,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
    activate: {
      description: "activate",
      arguments: z.object({}),
      execute: async (_args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["customerId"] !== undefined) {
          params["customerId"] = String(g["customerId"]);
        }
        if (g["subscriptionId"] !== undefined) {
          params["subscriptionId"] = String(g["subscriptionId"]);
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "reseller.subscriptions.activate",
            "path":
              "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/activate",
            "httpMethod": "POST",
            "parameterOrder": ["customerId", "subscriptionId"],
            "parameters": {
              "customerId": { "location": "path", "required": true },
              "subscriptionId": { "location": "path", "required": true },
            },
          },
          params,
          {},
        );
        return { result };
      },
    },
    change_plan: {
      description: "change plan",
      arguments: z.object({
        dealCode: z.any().optional(),
        kind: z.any().optional(),
        planName: z.any().optional(),
        purchaseOrderId: z.any().optional(),
        seats: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["customerId"] !== undefined) {
          params["customerId"] = String(g["customerId"]);
        }
        if (g["subscriptionId"] !== undefined) {
          params["subscriptionId"] = String(g["subscriptionId"]);
        }
        const body: Record<string, unknown> = {};
        if (args["dealCode"] !== undefined) body["dealCode"] = args["dealCode"];
        if (args["kind"] !== undefined) body["kind"] = args["kind"];
        if (args["planName"] !== undefined) body["planName"] = args["planName"];
        if (args["purchaseOrderId"] !== undefined) {
          body["purchaseOrderId"] = args["purchaseOrderId"];
        }
        if (args["seats"] !== undefined) body["seats"] = args["seats"];
        const result = await createResource(
          BASE_URL,
          {
            "id": "reseller.subscriptions.changePlan",
            "path":
              "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changePlan",
            "httpMethod": "POST",
            "parameterOrder": ["customerId", "subscriptionId"],
            "parameters": {
              "customerId": { "location": "path", "required": true },
              "subscriptionId": { "location": "path", "required": true },
            },
          },
          params,
          body,
        );
        return { result };
      },
    },
    change_renewal_settings: {
      description: "change renewal settings",
      arguments: z.object({
        kind: z.any().optional(),
        renewalType: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["customerId"] !== undefined) {
          params["customerId"] = String(g["customerId"]);
        }
        if (g["subscriptionId"] !== undefined) {
          params["subscriptionId"] = String(g["subscriptionId"]);
        }
        const body: Record<string, unknown> = {};
        if (args["kind"] !== undefined) body["kind"] = args["kind"];
        if (args["renewalType"] !== undefined) {
          body["renewalType"] = args["renewalType"];
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "reseller.subscriptions.changeRenewalSettings",
            "path":
              "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings",
            "httpMethod": "POST",
            "parameterOrder": ["customerId", "subscriptionId"],
            "parameters": {
              "customerId": { "location": "path", "required": true },
              "subscriptionId": { "location": "path", "required": true },
            },
          },
          params,
          body,
        );
        return { result };
      },
    },
    change_seats: {
      description: "change seats",
      arguments: z.object({
        kind: z.any().optional(),
        licensedNumberOfSeats: z.any().optional(),
        maximumNumberOfSeats: z.any().optional(),
        numberOfSeats: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["customerId"] !== undefined) {
          params["customerId"] = String(g["customerId"]);
        }
        if (g["subscriptionId"] !== undefined) {
          params["subscriptionId"] = String(g["subscriptionId"]);
        }
        const body: Record<string, unknown> = {};
        if (args["kind"] !== undefined) body["kind"] = args["kind"];
        if (args["licensedNumberOfSeats"] !== undefined) {
          body["licensedNumberOfSeats"] = args["licensedNumberOfSeats"];
        }
        if (args["maximumNumberOfSeats"] !== undefined) {
          body["maximumNumberOfSeats"] = args["maximumNumberOfSeats"];
        }
        if (args["numberOfSeats"] !== undefined) {
          body["numberOfSeats"] = args["numberOfSeats"];
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "reseller.subscriptions.changeSeats",
            "path":
              "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeSeats",
            "httpMethod": "POST",
            "parameterOrder": ["customerId", "subscriptionId"],
            "parameters": {
              "customerId": { "location": "path", "required": true },
              "subscriptionId": { "location": "path", "required": true },
            },
          },
          params,
          body,
        );
        return { result };
      },
    },
    start_paid_service: {
      description: "start paid service",
      arguments: z.object({}),
      execute: async (_args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["customerId"] !== undefined) {
          params["customerId"] = String(g["customerId"]);
        }
        if (g["subscriptionId"] !== undefined) {
          params["subscriptionId"] = String(g["subscriptionId"]);
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "reseller.subscriptions.startPaidService",
            "path":
              "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/startPaidService",
            "httpMethod": "POST",
            "parameterOrder": ["customerId", "subscriptionId"],
            "parameters": {
              "customerId": { "location": "path", "required": true },
              "subscriptionId": { "location": "path", "required": true },
            },
          },
          params,
          {},
        );
        return { result };
      },
    },
    suspend: {
      description: "suspend",
      arguments: z.object({}),
      execute: async (_args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["customerId"] !== undefined) {
          params["customerId"] = String(g["customerId"]);
        }
        if (g["subscriptionId"] !== undefined) {
          params["subscriptionId"] = String(g["subscriptionId"]);
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "reseller.subscriptions.suspend",
            "path":
              "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/suspend",
            "httpMethod": "POST",
            "parameterOrder": ["customerId", "subscriptionId"],
            "parameters": {
              "customerId": { "location": "path", "required": true },
              "subscriptionId": { "location": "path", "required": true },
            },
          },
          params,
          {},
        );
        return { result };
      },
    },
  },
};
