// Auto-generated extension model for @swamp/gcp/vault/matters
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

import { z } from "zod";
import {
  createResource,
  deleteResource,
  getProjectId,
  isResourceNotFoundError,
  readResource,
  updateResource,
} from "./_lib/gcp.ts";

const BASE_URL = "https://vault.googleapis.com/";

const GET_CONFIG = {
  "id": "vault.matters.get",
  "path": "v1/matters/{matterId}",
  "httpMethod": "GET",
  "parameterOrder": [
    "matterId",
  ],
  "parameters": {
    "matterId": {
      "location": "path",
      "required": true,
    },
    "view": {
      "location": "query",
    },
  },
} as const;

const INSERT_CONFIG = {
  "id": "vault.matters.create",
  "path": "v1/matters",
  "httpMethod": "POST",
  "parameterOrder": [],
  "parameters": {},
} as const;

const UPDATE_CONFIG = {
  "id": "vault.matters.update",
  "path": "v1/matters/{matterId}",
  "httpMethod": "PUT",
  "parameterOrder": [
    "matterId",
  ],
  "parameters": {
    "matterId": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const DELETE_CONFIG = {
  "id": "vault.matters.delete",
  "path": "v1/matters/{matterId}",
  "httpMethod": "DELETE",
  "parameterOrder": [
    "matterId",
  ],
  "parameters": {
    "matterId": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  description: z.string().describe("An optional description for the matter.")
    .optional(),
  matterId: z.string().describe(
    "The matter ID, which is generated by the server. Leave blank when creating a matter.",
  ).optional(),
  matterPermissions: z.array(z.object({
    accountId: z.string().describe(
      "The account ID, as provided by the [Admin SDK](https://developers.google.com/admin-sdk/).",
    ).optional(),
    role: z.enum(["ROLE_UNSPECIFIED", "COLLABORATOR", "OWNER"]).describe(
      "The user's role for the matter.",
    ).optional(),
  })).describe(
    "Lists the users and their permission for the matter. Currently there is no programmer defined limit on the number of permissions a matter can have.",
  ).optional(),
  matterRegion: z.enum(["MATTER_REGION_UNSPECIFIED", "ANY", "US", "EUROPE"])
    .describe("Optional. The requested data region for the matter.").optional(),
  name: z.string().describe("The name of the matter.").optional(),
  state: z.enum(["STATE_UNSPECIFIED", "OPEN", "CLOSED", "DELETED"]).describe(
    "The state of the matter.",
  ).optional(),
});

const StateSchema = z.object({
  description: z.string().optional(),
  matterId: z.string().optional(),
  matterPermissions: z.array(z.object({
    accountId: z.string(),
    role: z.string(),
  })).optional(),
  matterRegion: z.string().optional(),
  name: z.string(),
  state: z.string().optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  description: z.string().describe("An optional description for the matter.")
    .optional(),
  matterId: z.string().describe(
    "The matter ID, which is generated by the server. Leave blank when creating a matter.",
  ).optional(),
  matterPermissions: z.array(z.object({
    accountId: z.string().describe(
      "The account ID, as provided by the [Admin SDK](https://developers.google.com/admin-sdk/).",
    ).optional(),
    role: z.enum(["ROLE_UNSPECIFIED", "COLLABORATOR", "OWNER"]).describe(
      "The user's role for the matter.",
    ).optional(),
  })).describe(
    "Lists the users and their permission for the matter. Currently there is no programmer defined limit on the number of permissions a matter can have.",
  ).optional(),
  matterRegion: z.enum(["MATTER_REGION_UNSPECIFIED", "ANY", "US", "EUROPE"])
    .describe("Optional. The requested data region for the matter.").optional(),
  name: z.string().describe("The name of the matter.").optional(),
  state: z.enum(["STATE_UNSPECIFIED", "OPEN", "CLOSED", "DELETED"]).describe(
    "The state of the matter.",
  ).optional(),
});

export const model = {
  type: "@swamp/gcp/vault/matters",
  version: "2026.03.27.1",
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description:
        "Represents a matter. To work with Vault resources, the account must have the ...",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a matters",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const body: Record<string, unknown> = {};
        if (g["description"] !== undefined) {
          body["description"] = g["description"];
        }
        if (g["matterId"] !== undefined) body["matterId"] = g["matterId"];
        if (g["matterPermissions"] !== undefined) {
          body["matterPermissions"] = g["matterPermissions"];
        }
        if (g["matterRegion"] !== undefined) {
          body["matterRegion"] = g["matterRegion"];
        }
        if (g["name"] !== undefined) body["name"] = g["name"];
        if (g["state"] !== undefined) body["state"] = g["state"];
        if (g["name"] !== undefined) params["matterId"] = String(g["name"]);
        const result = await createResource(
          BASE_URL,
          INSERT_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const instanceName = (result.name ?? g.name)?.toString() ?? "current";
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a matters",
      arguments: z.object({
        identifier: z.string().describe("The name of the matters"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const g = context.globalArgs;
        params["matterId"] = args.identifier;
        const result = await readResource(
          BASE_URL,
          GET_CONFIG,
          params,
        ) as StateData;
        const instanceName = (result.name ?? g.name)?.toString() ??
          args.identifier;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update matters attributes",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const params: Record<string, string> = { project: projectId };
        params["matterId"] = existing["name"]?.toString() ?? "";
        const body: Record<string, unknown> = {};
        if (g["description"] !== undefined) {
          body["description"] = g["description"];
        }
        if (g["matterPermissions"] !== undefined) {
          body["matterPermissions"] = g["matterPermissions"];
        }
        if (g["matterRegion"] !== undefined) {
          body["matterRegion"] = g["matterRegion"];
        }
        if (g["name"] !== undefined) body["name"] = g["name"];
        if (g["state"] !== undefined) body["state"] = g["state"];
        for (const key of Object.keys(existing)) {
          if (
            key === "fingerprint" || key === "labelFingerprint" ||
            key === "etag" || key.endsWith("Fingerprint")
          ) {
            body[key] = existing[key];
          }
        }
        const result = await updateResource(
          BASE_URL,
          UPDATE_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete the matters",
      arguments: z.object({
        identifier: z.string().describe("The name of the matters"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        params["matterId"] = args.identifier;
        const { existed } = await deleteResource(
          BASE_URL,
          DELETE_CONFIG,
          params,
        );
        const instanceName = g.name?.toString() ?? args.identifier;
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync matters state from GCP",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { project: projectId };
          const identifier = existing.name?.toString() ?? g["name"]?.toString();
          if (!identifier) {
            throw new Error(
              "No identifier found in existing state or globalArgs",
            );
          }
          params["matterId"] = identifier;
          const result = await readResource(
            BASE_URL,
            GET_CONFIG,
            params,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
    add_permissions: {
      description: "add permissions",
      arguments: z.object({
        ccMe: z.any().optional(),
        matterPermission: z.any().optional(),
        sendEmails: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["matterId"] !== undefined) {
          params["matterId"] = String(g["matterId"]);
        }
        const body: Record<string, unknown> = {};
        if (args["ccMe"] !== undefined) body["ccMe"] = args["ccMe"];
        if (args["matterPermission"] !== undefined) {
          body["matterPermission"] = args["matterPermission"];
        }
        if (args["sendEmails"] !== undefined) {
          body["sendEmails"] = args["sendEmails"];
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "vault.matters.addPermissions",
            "path": "v1/matters/{matterId}:addPermissions",
            "httpMethod": "POST",
            "parameterOrder": ["matterId"],
            "parameters": {
              "matterId": { "location": "path", "required": true },
            },
          },
          params,
          body,
        );
        return { result };
      },
    },
    close: {
      description: "close",
      arguments: z.object({}),
      execute: async (_args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["matterId"] !== undefined) {
          params["matterId"] = String(g["matterId"]);
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "vault.matters.close",
            "path": "v1/matters/{matterId}:close",
            "httpMethod": "POST",
            "parameterOrder": ["matterId"],
            "parameters": {
              "matterId": { "location": "path", "required": true },
            },
          },
          params,
          {},
        );
        return { result };
      },
    },
    count: {
      description: "count",
      arguments: z.object({
        query: z.any().optional(),
        view: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["matterId"] !== undefined) {
          params["matterId"] = String(g["matterId"]);
        }
        const body: Record<string, unknown> = {};
        if (args["query"] !== undefined) body["query"] = args["query"];
        if (args["view"] !== undefined) body["view"] = args["view"];
        const result = await createResource(
          BASE_URL,
          {
            "id": "vault.matters.count",
            "path": "v1/matters/{matterId}:count",
            "httpMethod": "POST",
            "parameterOrder": ["matterId"],
            "parameters": {
              "matterId": { "location": "path", "required": true },
            },
          },
          params,
          body,
        );
        return { result };
      },
    },
    reopen: {
      description: "reopen",
      arguments: z.object({}),
      execute: async (_args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["matterId"] !== undefined) {
          params["matterId"] = String(g["matterId"]);
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "vault.matters.reopen",
            "path": "v1/matters/{matterId}:reopen",
            "httpMethod": "POST",
            "parameterOrder": ["matterId"],
            "parameters": {
              "matterId": { "location": "path", "required": true },
            },
          },
          params,
          {},
        );
        return { result };
      },
    },
    undelete: {
      description: "undelete",
      arguments: z.object({}),
      execute: async (_args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["matterId"] !== undefined) {
          params["matterId"] = String(g["matterId"]);
        }
        const result = await createResource(
          BASE_URL,
          {
            "id": "vault.matters.undelete",
            "path": "v1/matters/{matterId}:undelete",
            "httpMethod": "POST",
            "parameterOrder": ["matterId"],
            "parameters": {
              "matterId": { "location": "path", "required": true },
            },
          },
          params,
          {},
        );
        return { result };
      },
    },
  },
};
