// Auto-generated extension model for @swamp/aws/ec2/vpcendpoint
// Do not edit manually. Re-generate with: deno task generate:aws

// deno-lint-ignore-file no-explicit-any

import { z } from "zod";
import {
  createResource,
  deleteResource,
  isResourceNotFoundError,
  readResource,
  updateResource,
} from "./_lib/aws.ts";

export const TagSchema = z.object({
  Value: z.string().describe(
    "The value of the tag. Constraints: Tag values are case-sensitive and accept a maximum of 256 Unicode characters.",
  ),
  Key: z.string().describe(
    "The key of the tag. Constraints: Tag keys are case-sensitive and accept a maximum of 127 Unicode characters. May not begin with aws:.",
  ),
});

const GlobalArgsSchema = z.object({
  name: z.string().describe(
    "Instance name for this resource (used as the unique identifier in the factory pattern)",
  ),
  PrivateDnsEnabled: z.boolean().describe(
    "Indicate whether to associate a private hosted zone with the specified VPC. The private hosted zone contains a record set for the default public DNS name for the service for the Region (for example, kinesis.us-east-1.amazonaws.com), which resolves to the private IP addresses of the endpoint network interfaces in the VPC. This enables you to make requests to the default public DNS name for the service instead of the public DNS names that are automatically generated by the VPC endpoint service. To use a private hosted zone, you must set the following VPC attributes to true: enableDnsHostnames and enableDnsSupport. This property is supported only for interface endpoints. Default: false",
  ).optional(),
  IpAddressType: z.enum(["ipv4", "ipv6", "dualstack", "not-specified"])
    .describe("The supported IP address types.").optional(),
  ServiceRegion: z.string().describe("Describes a Region.").optional(),
  DnsOptions: z.object({
    PrivateDnsOnlyForInboundResolverEndpoint: z.enum([
      "OnlyInboundResolver",
      "AllResolvers",
      "NotSpecified",
    ]).describe(
      "Indicates whether to enable private DNS only for inbound endpoints. This option is available only for services that support both gateway and interface endpoints. It routes traffic that originates from the VPC to the gateway endpoint and traffic that originates from on-premises to the interface endpoint.",
    ).optional(),
    PrivateDnsSpecifiedDomains: z.array(z.string().min(1).max(255)).describe(
      "Indicates which of the private domains to create private hosted zones for and associate with the specified VPC. Only supported when private DNS is enabled and the private DNS preference is VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS or SPECIFIED_DOMAINS_ONLY.",
    ).optional(),
    DnsRecordIpType: z.enum([
      "ipv4",
      "ipv6",
      "dualstack",
      "service-defined",
      "not-specified",
    ]).describe("The DNS records created for the endpoint.").optional(),
    PrivateDnsPreference: z.enum([
      "VERIFIED_DOMAINS_ONLY",
      "ALL_DOMAINS",
      "VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS",
      "SPECIFIED_DOMAINS_ONLY",
    ]).describe(
      "The preference for which private domains have a private hosted zone created for and associated with the specified VPC. Only supported when private DNS is enabled and when the VPC endpoint type is ServiceNetwork or Resource.",
    ).optional(),
  }).describe("Describes the DNS options for an endpoint.").optional(),
  ResourceConfigurationArn: z.string().describe(
    "The Amazon Resource Name (ARN) of the resource configuration.",
  ).optional(),
  SecurityGroupIds: z.array(z.string()).describe(
    "The IDs of the security groups to associate with the endpoint network interfaces. If this parameter is not specified, we use the default security group for the VPC. Security groups are supported only for interface endpoints.",
  ).optional(),
  SubnetIds: z.array(z.string()).describe(
    "The IDs of the subnets in which to create endpoint network interfaces. You must specify this property for an interface endpoint or a Gateway Load Balancer endpoint. You can't specify this property for a gateway endpoint. For a Gateway Load Balancer endpoint, you can specify only one subnet.",
  ).optional(),
  ServiceNetworkArn: z.string().describe(
    "The Amazon Resource Name (ARN) of the service network.",
  ).optional(),
  VpcId: z.string().describe("The ID of the VPC."),
  RouteTableIds: z.array(z.string()).describe(
    "The IDs of the route tables. Routing is supported only for gateway endpoints.",
  ).optional(),
  ServiceName: z.string().describe("The name of the endpoint service.")
    .optional(),
  PolicyDocument: z.string().describe(
    'An endpoint policy, which controls access to the service from the VPC. The default endpoint policy allows full access to the service. Endpoint policies are supported only for gateway and interface endpoints. For CloudFormation templates in YAML, you can provide the policy in JSON or YAML format. For example, if you have a JSON policy, you can convert it to YAML before including it in the YAML template, and CFNlong converts the policy to JSON format before calling the API actions for privatelink. Alternatively, you can include the JSON directly in the YAML, as shown in the following Properties section: Properties: VpcEndpointType: \'Interface\' ServiceName:!Sub \'com.amazonaws.${AWS::Region}.logs\' PolicyDocument: \'{ "Version":"2012-10-17", "Statement": [{ "Effect":"Allow", "Principal":"*", "Action":["logs:Describe*","logs:Get*","logs:List*","logs:FilterLogEvents"], "Resource":"*" }] }\'',
  ).optional(),
  VpcEndpointType: z.enum([
    "Interface",
    "Gateway",
    "GatewayLoadBalancer",
    "ServiceNetwork",
    "Resource",
  ]).describe("The type of endpoint. Default: Gateway").optional(),
  Tags: z.array(TagSchema).describe("The tags to associate with the endpoint.")
    .optional(),
});

const StateSchema = z.object({
  PrivateDnsEnabled: z.boolean().optional(),
  IpAddressType: z.string().optional(),
  ServiceRegion: z.string().optional(),
  CreationTimestamp: z.string().optional(),
  DnsOptions: z.object({
    PrivateDnsOnlyForInboundResolverEndpoint: z.string(),
    PrivateDnsSpecifiedDomains: z.array(z.string()),
    DnsRecordIpType: z.string(),
    PrivateDnsPreference: z.string(),
  }).optional(),
  NetworkInterfaceIds: z.array(z.string()).optional(),
  DnsEntries: z.array(z.string()).optional(),
  ResourceConfigurationArn: z.string().optional(),
  SecurityGroupIds: z.array(z.string()).optional(),
  SubnetIds: z.array(z.string()).optional(),
  ServiceNetworkArn: z.string().optional(),
  VpcId: z.string().optional(),
  RouteTableIds: z.array(z.string()).optional(),
  ServiceName: z.string().optional(),
  PolicyDocument: z.string().optional(),
  VpcEndpointType: z.string().optional(),
  Id: z.string(),
  Tags: z.array(TagSchema).optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  name: z.string().optional(),
  PrivateDnsEnabled: z.boolean().describe(
    "Indicate whether to associate a private hosted zone with the specified VPC. The private hosted zone contains a record set for the default public DNS name for the service for the Region (for example, kinesis.us-east-1.amazonaws.com), which resolves to the private IP addresses of the endpoint network interfaces in the VPC. This enables you to make requests to the default public DNS name for the service instead of the public DNS names that are automatically generated by the VPC endpoint service. To use a private hosted zone, you must set the following VPC attributes to true: enableDnsHostnames and enableDnsSupport. This property is supported only for interface endpoints. Default: false",
  ).optional(),
  IpAddressType: z.enum(["ipv4", "ipv6", "dualstack", "not-specified"])
    .describe("The supported IP address types.").optional(),
  ServiceRegion: z.string().describe("Describes a Region.").optional(),
  DnsOptions: z.object({
    PrivateDnsOnlyForInboundResolverEndpoint: z.enum([
      "OnlyInboundResolver",
      "AllResolvers",
      "NotSpecified",
    ]).describe(
      "Indicates whether to enable private DNS only for inbound endpoints. This option is available only for services that support both gateway and interface endpoints. It routes traffic that originates from the VPC to the gateway endpoint and traffic that originates from on-premises to the interface endpoint.",
    ).optional(),
    PrivateDnsSpecifiedDomains: z.array(z.string().min(1).max(255)).describe(
      "Indicates which of the private domains to create private hosted zones for and associate with the specified VPC. Only supported when private DNS is enabled and the private DNS preference is VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS or SPECIFIED_DOMAINS_ONLY.",
    ).optional(),
    DnsRecordIpType: z.enum([
      "ipv4",
      "ipv6",
      "dualstack",
      "service-defined",
      "not-specified",
    ]).describe("The DNS records created for the endpoint.").optional(),
    PrivateDnsPreference: z.enum([
      "VERIFIED_DOMAINS_ONLY",
      "ALL_DOMAINS",
      "VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS",
      "SPECIFIED_DOMAINS_ONLY",
    ]).describe(
      "The preference for which private domains have a private hosted zone created for and associated with the specified VPC. Only supported when private DNS is enabled and when the VPC endpoint type is ServiceNetwork or Resource.",
    ).optional(),
  }).describe("Describes the DNS options for an endpoint.").optional(),
  ResourceConfigurationArn: z.string().describe(
    "The Amazon Resource Name (ARN) of the resource configuration.",
  ).optional(),
  SecurityGroupIds: z.array(z.string()).describe(
    "The IDs of the security groups to associate with the endpoint network interfaces. If this parameter is not specified, we use the default security group for the VPC. Security groups are supported only for interface endpoints.",
  ).optional(),
  SubnetIds: z.array(z.string()).describe(
    "The IDs of the subnets in which to create endpoint network interfaces. You must specify this property for an interface endpoint or a Gateway Load Balancer endpoint. You can't specify this property for a gateway endpoint. For a Gateway Load Balancer endpoint, you can specify only one subnet.",
  ).optional(),
  ServiceNetworkArn: z.string().describe(
    "The Amazon Resource Name (ARN) of the service network.",
  ).optional(),
  VpcId: z.string().describe("The ID of the VPC.").optional(),
  RouteTableIds: z.array(z.string()).describe(
    "The IDs of the route tables. Routing is supported only for gateway endpoints.",
  ).optional(),
  ServiceName: z.string().describe("The name of the endpoint service.")
    .optional(),
  PolicyDocument: z.string().describe(
    'An endpoint policy, which controls access to the service from the VPC. The default endpoint policy allows full access to the service. Endpoint policies are supported only for gateway and interface endpoints. For CloudFormation templates in YAML, you can provide the policy in JSON or YAML format. For example, if you have a JSON policy, you can convert it to YAML before including it in the YAML template, and CFNlong converts the policy to JSON format before calling the API actions for privatelink. Alternatively, you can include the JSON directly in the YAML, as shown in the following Properties section: Properties: VpcEndpointType: \'Interface\' ServiceName:!Sub \'com.amazonaws.${AWS::Region}.logs\' PolicyDocument: \'{ "Version":"2012-10-17", "Statement": [{ "Effect":"Allow", "Principal":"*", "Action":["logs:Describe*","logs:Get*","logs:List*","logs:FilterLogEvents"], "Resource":"*" }] }\'',
  ).optional(),
  VpcEndpointType: z.enum([
    "Interface",
    "Gateway",
    "GatewayLoadBalancer",
    "ServiceNetwork",
    "Resource",
  ]).describe("The type of endpoint. Default: Gateway").optional(),
  Tags: z.array(TagSchema).describe("The tags to associate with the endpoint.")
    .optional(),
});

export const model = {
  type: "@swamp/aws/ec2/vpcendpoint",
  version: "2026.04.03.2",
  upgrades: [
    {
      toVersion: "2026.04.01.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description: "EC2 VPCEndpoint resource state",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a EC2 VPCEndpoint",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const desiredState: Record<string, unknown> = {};
        for (const [key, value] of Object.entries(g)) {
          if (key === "name") continue;
          if (value !== undefined) desiredState[key] = value;
        }
        const result = await createResource(
          "AWS::EC2::VPCEndpoint",
          desiredState,
        ) as StateData;
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a EC2 VPCEndpoint",
      arguments: z.object({
        identifier: z.string().describe(
          "The primary identifier of the EC2 VPCEndpoint",
        ),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const result = await readResource(
          "AWS::EC2::VPCEndpoint",
          args.identifier,
        ) as StateData;
        const instanceName =
          (context.globalArgs.name?.toString() ?? args.identifier).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update a EC2 VPCEndpoint",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const identifier = existing.Id?.toString();
        if (!identifier) {
          throw new Error("No identifier found in existing state");
        }
        const currentState = await readResource(
          "AWS::EC2::VPCEndpoint",
          identifier,
        ) as StateData;
        const desiredState: Record<string, unknown> = { ...currentState };
        for (const [key, value] of Object.entries(g)) {
          if (key === "name") continue;
          if (value !== undefined) desiredState[key] = value;
        }
        const result = await updateResource(
          "AWS::EC2::VPCEndpoint",
          identifier,
          currentState,
          desiredState,
          [
            "ServiceName",
            "VpcEndpointType",
            "VpcId",
            "ServiceNetworkArn",
            "ResourceConfigurationArn",
            "ServiceRegion",
            "PrivateDnsPreference",
            "PrivateDnsSpecifiedDomains",
          ],
        );
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete a EC2 VPCEndpoint",
      arguments: z.object({
        identifier: z.string().describe(
          "The primary identifier of the EC2 VPCEndpoint",
        ),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const { existed } = await deleteResource(
          "AWS::EC2::VPCEndpoint",
          args.identifier,
        );
        const instanceName =
          (context.globalArgs.name?.toString() ?? args.identifier).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync EC2 VPCEndpoint state from AWS",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const identifier = existing.Id?.toString();
        if (!identifier) {
          throw new Error("No identifier found in existing state");
        }
        try {
          const result = await readResource(
            "AWS::EC2::VPCEndpoint",
            identifier,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              identifier,
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
  },
};
