// Auto-generated extension model for @swamp/gcp/contactcenterinsights/authorizedviewsets-authorizedviews-conversations-feedbacklabels
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

import { z } from "zod";
import {
  createResource,
  deleteResource,
  getProjectId,
  isResourceNotFoundError,
  readResource,
  updateResource,
} from "./_lib/gcp.ts";

/** Construct the fully-qualified resource name from parent and short name. */
function buildResourceName(parent: string, shortName: string): string {
  return `${parent}/feedbackLabels/${shortName}`;
}

const BASE_URL = "https://contactcenterinsights.googleapis.com/";

const GET_CONFIG = {
  "id":
    "contactcenterinsights.projects.locations.authorizedViewSets.authorizedViews.conversations.feedbackLabels.get",
  "path": "v1/{+name}",
  "httpMethod": "GET",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const INSERT_CONFIG = {
  "id":
    "contactcenterinsights.projects.locations.authorizedViewSets.authorizedViews.conversations.feedbackLabels.create",
  "path": "v1/{+parent}/feedbackLabels",
  "httpMethod": "POST",
  "parameterOrder": [
    "parent",
  ],
  "parameters": {
    "feedbackLabelId": {
      "location": "query",
    },
    "parent": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const PATCH_CONFIG = {
  "id":
    "contactcenterinsights.projects.locations.authorizedViewSets.authorizedViews.conversations.feedbackLabels.patch",
  "path": "v1/{+name}",
  "httpMethod": "PATCH",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
    "updateMask": {
      "location": "query",
    },
  },
} as const;

const DELETE_CONFIG = {
  "id":
    "contactcenterinsights.projects.locations.authorizedViewSets.authorizedViews.conversations.feedbackLabels.delete",
  "path": "v1/{+name}",
  "httpMethod": "DELETE",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  label: z.string().describe("String label used for Topic Modeling.")
    .optional(),
  labeledResource: z.string().describe(
    "Name of the resource to be labeled. Supported resources are: * `projects/{project}/locations/{location}/qaScorecards/{scorecard}/revisions/{revision}/qaQuestions/{question}` * `projects/{project}/locations/{location}/issueModels/{issue_model}` * `projects/{project}/locations/{location}/generators/{generator_id}`",
  ).optional(),
  name: z.string().describe(
    "Immutable. Resource name of the FeedbackLabel. Format: projects/{project}/locations/{location}/conversations/{conversation}/feedbackLabels/{feedback_label}",
  ).optional(),
  qaAnswerLabel: z.object({
    boolValue: z.boolean().describe("Boolean value.").optional(),
    key: z.string().describe(
      "A short string used as an identifier. Matches the value used in QaQuestion.AnswerChoice.key.",
    ).optional(),
    naValue: z.boolean().describe(
      'A value of "Not Applicable (N/A)". Should only ever be `true`.',
    ).optional(),
    normalizedScore: z.number().describe(
      "Output only. Normalized score of the questions. Calculated as score / potential_score.",
    ).optional(),
    numValue: z.number().describe("Numerical value.").optional(),
    potentialScore: z.number().describe(
      "Output only. The maximum potential score of the question.",
    ).optional(),
    score: z.number().describe("Output only. Numerical score of the answer.")
      .optional(),
    skipValue: z.boolean().describe(
      'Output only. A value of "Skip". If provided, this field may only be set to `true`. If a question receives this answer, it will be excluded from any score calculations. This would mean that the question was not evaluated.',
    ).optional(),
    strValue: z.string().describe("String value.").optional(),
  }).describe(
    "Message for holding the value of a QaAnswer. QaQuestion.AnswerChoice defines the possible answer values for a question.",
  ).optional(),
  feedbackLabelId: z.string().describe(
    "Optional. The ID of the feedback label to create. If one is not specified it will be generated by the server.",
  ).optional(),
  location: z.string().describe(
    "The location for this resource (e.g., 'us', 'us-central1', 'europe-west1')",
  ).optional(),
});

const StateSchema = z.object({
  createTime: z.string().optional(),
  label: z.string().optional(),
  labeledResource: z.string().optional(),
  name: z.string(),
  qaAnswerLabel: z.object({
    boolValue: z.boolean(),
    key: z.string(),
    naValue: z.boolean(),
    normalizedScore: z.number(),
    numValue: z.number(),
    potentialScore: z.number(),
    score: z.number(),
    skipValue: z.boolean(),
    strValue: z.string(),
  }).optional(),
  updateTime: z.string().optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  label: z.string().describe("String label used for Topic Modeling.")
    .optional(),
  labeledResource: z.string().describe(
    "Name of the resource to be labeled. Supported resources are: * `projects/{project}/locations/{location}/qaScorecards/{scorecard}/revisions/{revision}/qaQuestions/{question}` * `projects/{project}/locations/{location}/issueModels/{issue_model}` * `projects/{project}/locations/{location}/generators/{generator_id}`",
  ).optional(),
  name: z.string().describe(
    "Immutable. Resource name of the FeedbackLabel. Format: projects/{project}/locations/{location}/conversations/{conversation}/feedbackLabels/{feedback_label}",
  ).optional(),
  qaAnswerLabel: z.object({
    boolValue: z.boolean().describe("Boolean value.").optional(),
    key: z.string().describe(
      "A short string used as an identifier. Matches the value used in QaQuestion.AnswerChoice.key.",
    ).optional(),
    naValue: z.boolean().describe(
      'A value of "Not Applicable (N/A)". Should only ever be `true`.',
    ).optional(),
    normalizedScore: z.number().describe(
      "Output only. Normalized score of the questions. Calculated as score / potential_score.",
    ).optional(),
    numValue: z.number().describe("Numerical value.").optional(),
    potentialScore: z.number().describe(
      "Output only. The maximum potential score of the question.",
    ).optional(),
    score: z.number().describe("Output only. Numerical score of the answer.")
      .optional(),
    skipValue: z.boolean().describe(
      'Output only. A value of "Skip". If provided, this field may only be set to `true`. If a question receives this answer, it will be excluded from any score calculations. This would mean that the question was not evaluated.',
    ).optional(),
    strValue: z.string().describe("String value.").optional(),
  }).describe(
    "Message for holding the value of a QaAnswer. QaQuestion.AnswerChoice defines the possible answer values for a question.",
  ).optional(),
  feedbackLabelId: z.string().describe(
    "Optional. The ID of the feedback label to create. If one is not specified it will be generated by the server.",
  ).optional(),
  location: z.string().describe(
    "The location for this resource (e.g., 'us', 'us-central1', 'europe-west1')",
  ).optional(),
});

export const model = {
  type:
    "@swamp/gcp/contactcenterinsights/authorizedviewsets-authorizedviews-conversations-feedbacklabels",
  version: "2026.04.01.1",
  upgrades: [
    {
      toVersion: "2026.04.01.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description:
        "Represents a conversation, resource, and label provided by the user. Can take...",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a feedbackLabels",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["parent"] !== undefined) params["parent"] = String(g["parent"]);
        const body: Record<string, unknown> = {};
        if (g["label"] !== undefined) body["label"] = g["label"];
        if (g["labeledResource"] !== undefined) {
          body["labeledResource"] = g["labeledResource"];
        }
        if (g["name"] !== undefined) body["name"] = g["name"];
        if (g["qaAnswerLabel"] !== undefined) {
          body["qaAnswerLabel"] = g["qaAnswerLabel"];
        }
        if (g["feedbackLabelId"] !== undefined) {
          body["feedbackLabelId"] = g["feedbackLabelId"];
        }
        if (g["parent"] !== undefined && g["name"] !== undefined) {
          params["name"] = buildResourceName(
            String(g["parent"]),
            String(g["name"]),
          );
        }
        const result = await createResource(
          BASE_URL,
          INSERT_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const instanceName = (result.name ?? g.name)?.toString() ?? "current";
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a feedbackLabels",
      arguments: z.object({
        identifier: z.string().describe("The name of the feedbackLabels"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const g = context.globalArgs;
        params["name"] = buildResourceName(
          String(g["parent"] ?? ""),
          args.identifier,
        );
        const result = await readResource(
          BASE_URL,
          GET_CONFIG,
          params,
        ) as StateData;
        const instanceName = (result.name ?? g.name)?.toString() ??
          args.identifier;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update feedbackLabels attributes",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const params: Record<string, string> = { project: projectId };
        params["name"] = buildResourceName(
          String(g["parent"] ?? ""),
          existing["name"]?.toString() ?? g["name"]?.toString() ?? "",
        );
        const body: Record<string, unknown> = {};
        if (g["label"] !== undefined) body["label"] = g["label"];
        if (g["labeledResource"] !== undefined) {
          body["labeledResource"] = g["labeledResource"];
        }
        if (g["qaAnswerLabel"] !== undefined) {
          body["qaAnswerLabel"] = g["qaAnswerLabel"];
        }
        for (const key of Object.keys(existing)) {
          if (
            key === "fingerprint" || key === "labelFingerprint" ||
            key === "etag" || key.endsWith("Fingerprint")
          ) {
            body[key] = existing[key];
          }
        }
        const result = await updateResource(
          BASE_URL,
          PATCH_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete the feedbackLabels",
      arguments: z.object({
        identifier: z.string().describe("The name of the feedbackLabels"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        params["name"] = buildResourceName(
          String(g["parent"] ?? ""),
          args.identifier,
        );
        const { existed } = await deleteResource(
          BASE_URL,
          DELETE_CONFIG,
          params,
        );
        const instanceName = g.name?.toString() ?? args.identifier;
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync feedbackLabels state from GCP",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { project: projectId };
          const shortName = existing.name?.toString() ?? g["name"]?.toString();
          if (!shortName) throw new Error("No identifier found");
          params["name"] = buildResourceName(
            String(g["parent"] ?? ""),
            shortName,
          );
          const result = await readResource(
            BASE_URL,
            GET_CONFIG,
            params,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
  },
};
