// Auto-generated extension model for @swamp/gcp/apigee/securitymonitoringconditions
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

import { z } from "zod";
import {
  createResource,
  deleteResource,
  getProjectId,
  isResourceNotFoundError,
  readResource,
  updateResource,
} from "./_lib/gcp.ts";

/** Construct the fully-qualified resource name from parent and short name. */
function buildResourceName(parent: string, shortName: string): string {
  return `${parent}/securityMonitoringConditions/${shortName}`;
}

const BASE_URL = "https://apigee.googleapis.com/";

const GET_CONFIG = {
  "id": "apigee.organizations.securityMonitoringConditions.get",
  "path": "v1/{+name}",
  "httpMethod": "GET",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
    "riskAssessmentType": {
      "location": "query",
    },
  },
} as const;

const INSERT_CONFIG = {
  "id": "apigee.organizations.securityMonitoringConditions.create",
  "path": "v1/{+parent}/securityMonitoringConditions",
  "httpMethod": "POST",
  "parameterOrder": [
    "parent",
  ],
  "parameters": {
    "parent": {
      "location": "path",
      "required": true,
    },
    "securityMonitoringConditionId": {
      "location": "query",
    },
  },
} as const;

const PATCH_CONFIG = {
  "id": "apigee.organizations.securityMonitoringConditions.patch",
  "path": "v1/{+name}",
  "httpMethod": "PATCH",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
    "updateMask": {
      "location": "query",
    },
  },
} as const;

const DELETE_CONFIG = {
  "id": "apigee.organizations.securityMonitoringConditions.delete",
  "path": "v1/{+name}",
  "httpMethod": "DELETE",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
    "riskAssessmentType": {
      "location": "query",
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  apiHubGateway: z.string().describe(
    "Optional. The API Hub gateway monitored by the security monitoring condition. This should only be set if risk_assessment_type is API_HUB. Format: `projects/{project}/locations/{location}/plugins/{plugin}/instances/{instance}`",
  ).optional(),
  include: z.object({
    resources: z.array(z.object({
      name: z.string().describe(
        "Required. Name of this resource. For an Apigee API Proxy, this should be the id of the API proxy. For an API Hub Deployment, this should be the id of the deployment.",
      ).optional(),
      type: z.enum([
        "RESOURCE_TYPE_UNSPECIFIED",
        "API_PROXY",
        "API_HUB_DEPLOYMENT",
      ]).describe("Required. Type of this resource.").optional(),
    })).describe(
      "Required. The array of resources. For Apigee, the proxies are resources.",
    ).optional(),
  }).describe(
    "Message for the array of resources. For Apigee, the proxies are resources.",
  ).optional(),
  includeAllResources: z.object({}).describe(
    "Message for include_all_resources option.",
  ).optional(),
  name: z.string().describe(
    "Identifier. Name of the security monitoring condition resource. Format: organizations/{org}/securityMonitoringConditions/{security_monitoring_condition}",
  ).optional(),
  profile: z.string().describe(
    "Required. ID of security profile of the security monitoring condition.",
  ).optional(),
  riskAssessmentType: z.enum([
    "RISK_ASSESSMENT_TYPE_UNSPECIFIED",
    "APIGEE",
    "API_HUB",
  ]).describe(
    "Optional. The risk assessment type of the security monitoring condition. Defaults to ADVANCED_API_SECURITY.",
  ).optional(),
  scope: z.string().describe(
    "Optional. Scope of the security monitoring condition. When RiskAssessmentType is APIGEE, the scope should be set to the environment of the resources. When RiskAssessmentType is API_HUB, the scope should not be set.",
  ).optional(),
  securityMonitoringConditionId: z.string().describe(
    "Optional. Optional: The security monitoring condition id. If not specified, a monitoring condition uuid will be generated by the backend. This value should be 4-63 characters, and valid characters are /a-z-/.",
  ).optional(),
  parent: z.string().describe(
    "The parent resource name (e.g., projects/my-project/locations/us-central1, organizations/123, folders/456)",
  ).optional(),
});

const StateSchema = z.object({
  apiHubGateway: z.string().optional(),
  createTime: z.string().optional(),
  include: z.object({
    resources: z.array(z.object({
      name: z.string(),
      type: z.string(),
    })),
  }).optional(),
  includeAllResources: z.object({}).optional(),
  name: z.string(),
  profile: z.string().optional(),
  riskAssessmentType: z.string().optional(),
  scope: z.string().optional(),
  totalDeployedResources: z.number().optional(),
  totalMonitoredResources: z.number().optional(),
  updateTime: z.string().optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  apiHubGateway: z.string().describe(
    "Optional. The API Hub gateway monitored by the security monitoring condition. This should only be set if risk_assessment_type is API_HUB. Format: `projects/{project}/locations/{location}/plugins/{plugin}/instances/{instance}`",
  ).optional(),
  include: z.object({
    resources: z.array(z.object({
      name: z.string().describe(
        "Required. Name of this resource. For an Apigee API Proxy, this should be the id of the API proxy. For an API Hub Deployment, this should be the id of the deployment.",
      ).optional(),
      type: z.enum([
        "RESOURCE_TYPE_UNSPECIFIED",
        "API_PROXY",
        "API_HUB_DEPLOYMENT",
      ]).describe("Required. Type of this resource.").optional(),
    })).describe(
      "Required. The array of resources. For Apigee, the proxies are resources.",
    ).optional(),
  }).describe(
    "Message for the array of resources. For Apigee, the proxies are resources.",
  ).optional(),
  includeAllResources: z.object({}).describe(
    "Message for include_all_resources option.",
  ).optional(),
  name: z.string().describe(
    "Identifier. Name of the security monitoring condition resource. Format: organizations/{org}/securityMonitoringConditions/{security_monitoring_condition}",
  ).optional(),
  profile: z.string().describe(
    "Required. ID of security profile of the security monitoring condition.",
  ).optional(),
  riskAssessmentType: z.enum([
    "RISK_ASSESSMENT_TYPE_UNSPECIFIED",
    "APIGEE",
    "API_HUB",
  ]).describe(
    "Optional. The risk assessment type of the security monitoring condition. Defaults to ADVANCED_API_SECURITY.",
  ).optional(),
  scope: z.string().describe(
    "Optional. Scope of the security monitoring condition. When RiskAssessmentType is APIGEE, the scope should be set to the environment of the resources. When RiskAssessmentType is API_HUB, the scope should not be set.",
  ).optional(),
  securityMonitoringConditionId: z.string().describe(
    "Optional. Optional: The security monitoring condition id. If not specified, a monitoring condition uuid will be generated by the backend. This value should be 4-63 characters, and valid characters are /a-z-/.",
  ).optional(),
  parent: z.string().describe(
    "The parent resource name (e.g., projects/my-project/locations/us-central1, organizations/123, folders/456)",
  ).optional(),
});

export const model = {
  type: "@swamp/gcp/apigee/securitymonitoringconditions",
  version: "2026.04.02.2",
  upgrades: [
    {
      toVersion: "2026.04.01.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.02.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],

  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description:
        "Security monitoring condition for risk assessment version 2.",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a securityMonitoringConditions",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["parent"] !== undefined) params["parent"] = String(g["parent"]);
        const body: Record<string, unknown> = {};
        if (g["apiHubGateway"] !== undefined) {
          body["apiHubGateway"] = g["apiHubGateway"];
        }
        if (g["include"] !== undefined) body["include"] = g["include"];
        if (g["includeAllResources"] !== undefined) {
          body["includeAllResources"] = g["includeAllResources"];
        }
        if (g["name"] !== undefined) body["name"] = g["name"];
        if (g["profile"] !== undefined) body["profile"] = g["profile"];
        if (g["riskAssessmentType"] !== undefined) {
          body["riskAssessmentType"] = g["riskAssessmentType"];
        }
        if (g["scope"] !== undefined) body["scope"] = g["scope"];
        if (g["securityMonitoringConditionId"] !== undefined) {
          body["securityMonitoringConditionId"] =
            g["securityMonitoringConditionId"];
        }
        if (g["parent"] !== undefined && g["name"] !== undefined) {
          params["name"] = buildResourceName(
            String(g["parent"]),
            String(g["name"]),
          );
        }
        const result = await createResource(
          BASE_URL,
          INSERT_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const instanceName = (result.name ?? g.name)?.toString() ?? "current";
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a securityMonitoringConditions",
      arguments: z.object({
        identifier: z.string().describe(
          "The name of the securityMonitoringConditions",
        ),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const g = context.globalArgs;
        params["name"] = buildResourceName(
          String(g["parent"] ?? ""),
          args.identifier,
        );
        const result = await readResource(
          BASE_URL,
          GET_CONFIG,
          params,
        ) as StateData;
        const instanceName = (result.name ?? g.name)?.toString() ??
          args.identifier;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update securityMonitoringConditions attributes",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const params: Record<string, string> = { project: projectId };
        params["name"] = buildResourceName(
          String(g["parent"] ?? ""),
          existing["name"]?.toString() ?? g["name"]?.toString() ?? "",
        );
        const body: Record<string, unknown> = {};
        if (g["apiHubGateway"] !== undefined) {
          body["apiHubGateway"] = g["apiHubGateway"];
        }
        if (g["include"] !== undefined) body["include"] = g["include"];
        if (g["includeAllResources"] !== undefined) {
          body["includeAllResources"] = g["includeAllResources"];
        }
        if (g["profile"] !== undefined) body["profile"] = g["profile"];
        if (g["riskAssessmentType"] !== undefined) {
          body["riskAssessmentType"] = g["riskAssessmentType"];
        }
        if (g["scope"] !== undefined) body["scope"] = g["scope"];
        for (const key of Object.keys(existing)) {
          if (
            key === "fingerprint" || key === "labelFingerprint" ||
            key === "etag" || key.endsWith("Fingerprint")
          ) {
            body[key] = existing[key];
          }
        }
        const result = await updateResource(
          BASE_URL,
          PATCH_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete the securityMonitoringConditions",
      arguments: z.object({
        identifier: z.string().describe(
          "The name of the securityMonitoringConditions",
        ),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        params["name"] = buildResourceName(
          String(g["parent"] ?? ""),
          args.identifier,
        );
        const { existed } = await deleteResource(
          BASE_URL,
          DELETE_CONFIG,
          params,
        );
        const instanceName = g.name?.toString() ?? args.identifier;
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync securityMonitoringConditions state from GCP",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { project: projectId };
          const shortName = existing.name?.toString() ?? g["name"]?.toString();
          if (!shortName) throw new Error("No identifier found");
          params["name"] = buildResourceName(
            String(g["parent"] ?? ""),
            shortName,
          );
          const result = await readResource(
            BASE_URL,
            GET_CONFIG,
            params,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
  },
};
