// Auto-generated extension model for @swamp/gcp/meet/spaces
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

import { z } from "zod";
import {
  createResource,
  getProjectId,
  isResourceNotFoundError,
  readResource,
  updateResource,
} from "./_lib/gcp.ts";

const BASE_URL = "https://meet.googleapis.com/";

const GET_CONFIG = {
  "id": "meet.spaces.get",
  "path": "v2/{+name}",
  "httpMethod": "GET",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const INSERT_CONFIG = {
  "id": "meet.spaces.create",
  "path": "v2/spaces",
  "httpMethod": "POST",
  "parameterOrder": [],
  "parameters": {},
} as const;

const PATCH_CONFIG = {
  "id": "meet.spaces.patch",
  "path": "v2/{+name}",
  "httpMethod": "PATCH",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
    "updateMask": {
      "location": "query",
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  activeConference: z.object({
    conferenceRecord: z.string().describe(
      "Output only. Reference to 'ConferenceRecord' resource. Format: `conferenceRecords/{conference_record}` where `{conference_record}` is a unique ID for each instance of a call within a space.",
    ).optional(),
  }).describe("Active conference.").optional(),
  config: z.object({
    accessType: z.enum([
      "ACCESS_TYPE_UNSPECIFIED",
      "OPEN",
      "TRUSTED",
      "RESTRICTED",
    ]).describe(
      "Access type of the meeting space that determines who can join without knocking. Default: The user's default access settings. Controlled by the user's admin for enterprise users or RESTRICTED.",
    ).optional(),
    artifactConfig: z.object({
      recordingConfig: z.object({
        autoRecordingGeneration: z.enum([
          "AUTO_GENERATION_TYPE_UNSPECIFIED",
          "ON",
          "OFF",
        ]).describe(
          "Defines whether a meeting space is automatically recorded when someone with the privilege to record joins the meeting.",
        ).optional(),
      }).describe("Configuration related to recording in a meeting space.")
        .optional(),
      smartNotesConfig: z.object({
        autoSmartNotesGeneration: z.enum([
          "AUTO_GENERATION_TYPE_UNSPECIFIED",
          "ON",
          "OFF",
        ]).describe(
          "Defines whether to automatically generate a summary and recap of the meeting for all invitees in the organization when someone with the privilege to enable smart notes joins the meeting.",
        ).optional(),
      }).describe(
        'Configuration related to smart notes in a meeting space. For more information about smart notes, see ["Take notes for me" in Google Meet](https://support.google.com/meet/answer/14754931).',
      ).optional(),
      transcriptionConfig: z.object({
        autoTranscriptionGeneration: z.enum([
          "AUTO_GENERATION_TYPE_UNSPECIFIED",
          "ON",
          "OFF",
        ]).describe(
          "Defines whether the content of a meeting is automatically transcribed when someone with the privilege to transcribe joins the meeting.",
        ).optional(),
      }).describe("Configuration related to transcription in a meeting space.")
        .optional(),
    }).describe(
      "Configuration related to meeting artifacts potentially generated by this meeting space.",
    ).optional(),
    attendanceReportGenerationType: z.enum([
      "ATTENDANCE_REPORT_GENERATION_TYPE_UNSPECIFIED",
      "GENERATE_REPORT",
      "DO_NOT_GENERATE",
    ]).describe("Whether attendance report is enabled for the meeting space.")
      .optional(),
    entryPointAccess: z.enum([
      "ENTRY_POINT_ACCESS_UNSPECIFIED",
      "ALL",
      "CREATOR_APP_ONLY",
    ]).describe(
      "Defines the entry points that can be used to join meetings hosted in this meeting space. Default: EntryPointAccess.ALL",
    ).optional(),
    moderation: z.enum(["MODERATION_UNSPECIFIED", "OFF", "ON"]).describe(
      "The pre-configured moderation mode for the Meeting. Default: Controlled by the user's policies.",
    ).optional(),
    moderationRestrictions: z.object({
      chatRestriction: z.enum([
        "RESTRICTION_TYPE_UNSPECIFIED",
        "HOSTS_ONLY",
        "NO_RESTRICTION",
      ]).describe(
        "Defines who has permission to send chat messages in the meeting space.",
      ).optional(),
      defaultJoinAsViewerType: z.enum([
        "DEFAULT_JOIN_AS_VIEWER_TYPE_UNSPECIFIED",
        "ON",
        "OFF",
      ]).describe(
        "Defines whether to restrict the default role assigned to users as viewer.",
      ).optional(),
      presentRestriction: z.enum([
        "RESTRICTION_TYPE_UNSPECIFIED",
        "HOSTS_ONLY",
        "NO_RESTRICTION",
      ]).describe(
        "Defines who has permission to share their screen in the meeting space.",
      ).optional(),
      reactionRestriction: z.enum([
        "RESTRICTION_TYPE_UNSPECIFIED",
        "HOSTS_ONLY",
        "NO_RESTRICTION",
      ]).describe(
        "Defines who has permission to send reactions in the meeting space.",
      ).optional(),
    }).describe(
      "Defines restrictions for features when the meeting is moderated.",
    ).optional(),
  }).describe("The configuration pertaining to a meeting space.").optional(),
  name: z.string().describe(
    "Immutable. Resource name of the space. Format: `spaces/{space}`. `{space}` is the resource identifier for the space. It's a unique, server-generated ID and is case sensitive. For example, `jQCFfuBOdN5z`. For more information, see [How Meet identifies a meeting space](https://developers.google.com/workspace/meet/api/guides/meeting-spaces#identify-meeting-space).",
  ).optional(),
});

const StateSchema = z.object({
  activeConference: z.object({
    conferenceRecord: z.string(),
  }).optional(),
  config: z.object({
    accessType: z.string(),
    artifactConfig: z.object({
      recordingConfig: z.object({
        autoRecordingGeneration: z.string(),
      }),
      smartNotesConfig: z.object({
        autoSmartNotesGeneration: z.string(),
      }),
      transcriptionConfig: z.object({
        autoTranscriptionGeneration: z.string(),
      }),
    }),
    attendanceReportGenerationType: z.string(),
    entryPointAccess: z.string(),
    moderation: z.string(),
    moderationRestrictions: z.object({
      chatRestriction: z.string(),
      defaultJoinAsViewerType: z.string(),
      presentRestriction: z.string(),
      reactionRestriction: z.string(),
    }),
  }).optional(),
  gatewaySipAccess: z.array(z.object({
    sipAccessCode: z.string(),
    uri: z.string(),
  })).optional(),
  meetingCode: z.string().optional(),
  meetingUri: z.string().optional(),
  name: z.string(),
  phoneAccess: z.array(z.object({
    languageCode: z.string(),
    phoneNumber: z.string(),
    pin: z.string(),
    regionCode: z.string(),
  })).optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  activeConference: z.object({
    conferenceRecord: z.string().describe(
      "Output only. Reference to 'ConferenceRecord' resource. Format: `conferenceRecords/{conference_record}` where `{conference_record}` is a unique ID for each instance of a call within a space.",
    ).optional(),
  }).describe("Active conference.").optional(),
  config: z.object({
    accessType: z.enum([
      "ACCESS_TYPE_UNSPECIFIED",
      "OPEN",
      "TRUSTED",
      "RESTRICTED",
    ]).describe(
      "Access type of the meeting space that determines who can join without knocking. Default: The user's default access settings. Controlled by the user's admin for enterprise users or RESTRICTED.",
    ).optional(),
    artifactConfig: z.object({
      recordingConfig: z.object({
        autoRecordingGeneration: z.enum([
          "AUTO_GENERATION_TYPE_UNSPECIFIED",
          "ON",
          "OFF",
        ]).describe(
          "Defines whether a meeting space is automatically recorded when someone with the privilege to record joins the meeting.",
        ).optional(),
      }).describe("Configuration related to recording in a meeting space.")
        .optional(),
      smartNotesConfig: z.object({
        autoSmartNotesGeneration: z.enum([
          "AUTO_GENERATION_TYPE_UNSPECIFIED",
          "ON",
          "OFF",
        ]).describe(
          "Defines whether to automatically generate a summary and recap of the meeting for all invitees in the organization when someone with the privilege to enable smart notes joins the meeting.",
        ).optional(),
      }).describe(
        'Configuration related to smart notes in a meeting space. For more information about smart notes, see ["Take notes for me" in Google Meet](https://support.google.com/meet/answer/14754931).',
      ).optional(),
      transcriptionConfig: z.object({
        autoTranscriptionGeneration: z.enum([
          "AUTO_GENERATION_TYPE_UNSPECIFIED",
          "ON",
          "OFF",
        ]).describe(
          "Defines whether the content of a meeting is automatically transcribed when someone with the privilege to transcribe joins the meeting.",
        ).optional(),
      }).describe("Configuration related to transcription in a meeting space.")
        .optional(),
    }).describe(
      "Configuration related to meeting artifacts potentially generated by this meeting space.",
    ).optional(),
    attendanceReportGenerationType: z.enum([
      "ATTENDANCE_REPORT_GENERATION_TYPE_UNSPECIFIED",
      "GENERATE_REPORT",
      "DO_NOT_GENERATE",
    ]).describe("Whether attendance report is enabled for the meeting space.")
      .optional(),
    entryPointAccess: z.enum([
      "ENTRY_POINT_ACCESS_UNSPECIFIED",
      "ALL",
      "CREATOR_APP_ONLY",
    ]).describe(
      "Defines the entry points that can be used to join meetings hosted in this meeting space. Default: EntryPointAccess.ALL",
    ).optional(),
    moderation: z.enum(["MODERATION_UNSPECIFIED", "OFF", "ON"]).describe(
      "The pre-configured moderation mode for the Meeting. Default: Controlled by the user's policies.",
    ).optional(),
    moderationRestrictions: z.object({
      chatRestriction: z.enum([
        "RESTRICTION_TYPE_UNSPECIFIED",
        "HOSTS_ONLY",
        "NO_RESTRICTION",
      ]).describe(
        "Defines who has permission to send chat messages in the meeting space.",
      ).optional(),
      defaultJoinAsViewerType: z.enum([
        "DEFAULT_JOIN_AS_VIEWER_TYPE_UNSPECIFIED",
        "ON",
        "OFF",
      ]).describe(
        "Defines whether to restrict the default role assigned to users as viewer.",
      ).optional(),
      presentRestriction: z.enum([
        "RESTRICTION_TYPE_UNSPECIFIED",
        "HOSTS_ONLY",
        "NO_RESTRICTION",
      ]).describe(
        "Defines who has permission to share their screen in the meeting space.",
      ).optional(),
      reactionRestriction: z.enum([
        "RESTRICTION_TYPE_UNSPECIFIED",
        "HOSTS_ONLY",
        "NO_RESTRICTION",
      ]).describe(
        "Defines who has permission to send reactions in the meeting space.",
      ).optional(),
    }).describe(
      "Defines restrictions for features when the meeting is moderated.",
    ).optional(),
  }).describe("The configuration pertaining to a meeting space.").optional(),
  name: z.string().describe(
    "Immutable. Resource name of the space. Format: `spaces/{space}`. `{space}` is the resource identifier for the space. It's a unique, server-generated ID and is case sensitive. For example, `jQCFfuBOdN5z`. For more information, see [How Meet identifies a meeting space](https://developers.google.com/workspace/meet/api/guides/meeting-spaces#identify-meeting-space).",
  ).optional(),
});

export const model = {
  type: "@swamp/gcp/meet/spaces",
  version: "2026.04.03.3",
  upgrades: [
    {
      toVersion: "2026.04.01.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.01.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.02.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.02.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.3",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description:
        "Virtual place where conferences are held. Only one active conference can be h...",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a spaces",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const body: Record<string, unknown> = {};
        if (g["activeConference"] !== undefined) {
          body["activeConference"] = g["activeConference"];
        }
        if (g["config"] !== undefined) body["config"] = g["config"];
        if (g["name"] !== undefined) body["name"] = g["name"];
        if (g["name"] !== undefined) params["name"] = String(g["name"]);
        const result = await createResource(
          BASE_URL,
          INSERT_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const instanceName = ((result.name ?? g.name)?.toString() ?? "current")
          .replace(/[\/\\]/g, "_").replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a spaces",
      arguments: z.object({
        identifier: z.string().describe("The name of the spaces"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const g = context.globalArgs;
        params["name"] = args.identifier;
        const result = await readResource(
          BASE_URL,
          GET_CONFIG,
          params,
        ) as StateData;
        const instanceName =
          ((result.name ?? g.name)?.toString() ?? args.identifier).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update spaces attributes",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const params: Record<string, string> = { project: projectId };
        params["name"] = existing["name"]?.toString() ?? "";
        const body: Record<string, unknown> = {};
        if (g["activeConference"] !== undefined) {
          body["activeConference"] = g["activeConference"];
        }
        if (g["config"] !== undefined) body["config"] = g["config"];
        for (const key of Object.keys(existing)) {
          if (
            key === "fingerprint" || key === "labelFingerprint" ||
            key === "etag" || key.endsWith("Fingerprint")
          ) {
            body[key] = existing[key];
          }
        }
        const result = await updateResource(
          BASE_URL,
          PATCH_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync spaces state from GCP",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { project: projectId };
          const identifier = existing.name?.toString() ?? g["name"]?.toString();
          if (!identifier) {
            throw new Error(
              "No identifier found in existing state or globalArgs",
            );
          }
          params["name"] = identifier;
          const result = await readResource(
            BASE_URL,
            GET_CONFIG,
            params,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
    end_active_conference: {
      description: "end active conference",
      arguments: z.object({}),
      execute: async (_args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        if (g["name"] !== undefined) params["name"] = String(g["name"]);
        const result = await createResource(
          BASE_URL,
          {
            "id": "meet.spaces.endActiveConference",
            "path": "v2/{+name}:endActiveConference",
            "httpMethod": "POST",
            "parameterOrder": ["name"],
            "parameters": { "name": { "location": "path", "required": true } },
          },
          params,
          {},
        );
        return { result };
      },
    },
  },
};
