// Auto-generated extension model for @swamp/aws/quicksight/custom-permissions
// Do not edit manually. Re-generate with: deno task generate:aws

// deno-lint-ignore-file no-explicit-any

import { z } from "zod";
import {
  createResource,
  deleteResource,
  isResourceNotFoundError,
  readResource,
  updateResource,
} from "./_lib/aws.ts";

export const TagSchema = z.object({
  Key: z.string().min(1).max(128).describe("Tag key."),
  Value: z.string().min(1).max(256).describe("Tag value."),
});

const GlobalArgsSchema = z.object({
  name: z.string().describe(
    "Instance name for this resource (used as the unique identifier in the factory pattern)",
  ),
  AwsAccountId: z.string().min(12).max(12).regex(new RegExp("^[0-9]{12}$")),
  Capabilities: z.object({
    ExportToCsv: z.enum(["DENY"]).optional(),
    ExportToExcel: z.enum(["DENY"]).optional(),
    ExportToPdf: z.enum(["DENY"]).optional(),
    PrintReports: z.enum(["DENY"]).optional(),
    CreateAndUpdateThemes: z.enum(["DENY"]).optional(),
    AddOrRunAnomalyDetectionForAnalyses: z.enum(["DENY"]).optional(),
    ShareAnalyses: z.enum(["DENY"]).optional(),
    CreateAndUpdateDatasets: z.enum(["DENY"]).optional(),
    ShareDatasets: z.enum(["DENY"]).optional(),
    SubscribeDashboardEmailReports: z.enum(["DENY"]).optional(),
    CreateAndUpdateDashboardEmailReports: z.enum(["DENY"]).optional(),
    ShareDashboards: z.enum(["DENY"]).optional(),
    CreateAndUpdateThresholdAlerts: z.enum(["DENY"]).optional(),
    RenameSharedFolders: z.enum(["DENY"]).optional(),
    CreateSharedFolders: z.enum(["DENY"]).optional(),
    CreateAndUpdateDataSources: z.enum(["DENY"]).optional(),
    ShareDataSources: z.enum(["DENY"]).optional(),
    ViewAccountSPICECapacity: z.enum(["DENY"]).optional(),
    CreateSPICEDataset: z.enum(["DENY"]).optional(),
    ExportToPdfInScheduledReports: z.enum(["DENY"]).optional(),
    ExportToCsvInScheduledReports: z.enum(["DENY"]).optional(),
    ExportToExcelInScheduledReports: z.enum(["DENY"]).optional(),
    IncludeContentInScheduledReportsEmail: z.enum(["DENY"]).optional(),
    Dashboard: z.enum(["DENY"]).optional(),
    Analysis: z.enum(["DENY"]).optional(),
    Automate: z.enum(["DENY"]).optional(),
    Flow: z.enum(["DENY"]).optional(),
    PublishWithoutApproval: z.enum(["DENY"]).optional(),
    UseBedrockModels: z.enum(["DENY"]).optional(),
    PerformFlowUiTask: z.enum(["DENY"]).optional(),
    ApproveFlowShareRequests: z.enum(["DENY"]).optional(),
    UseAgentWebSearch: z.enum(["DENY"]).optional(),
    KnowledgeBase: z.enum(["DENY"]).optional(),
    CreateAndUpdateKnowledgeBases: z.enum(["DENY"]).optional(),
    ShareKnowledgeBases: z.enum(["DENY"]).optional(),
    Action: z.enum(["DENY"]).optional(),
    GenericHTTPAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateGenericHTTPAction: z.enum(["DENY"]).optional(),
    ShareGenericHTTPAction: z.enum(["DENY"]).optional(),
    UseGenericHTTPAction: z.enum(["DENY"]).optional(),
    AsanaAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAsanaAction: z.enum(["DENY"]).optional(),
    ShareAsanaAction: z.enum(["DENY"]).optional(),
    UseAsanaAction: z.enum(["DENY"]).optional(),
    SlackAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSlackAction: z.enum(["DENY"]).optional(),
    ShareSlackAction: z.enum(["DENY"]).optional(),
    UseSlackAction: z.enum(["DENY"]).optional(),
    ServiceNowAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateServiceNowAction: z.enum(["DENY"]).optional(),
    ShareServiceNowAction: z.enum(["DENY"]).optional(),
    UseServiceNowAction: z.enum(["DENY"]).optional(),
    SalesforceAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSalesforceAction: z.enum(["DENY"]).optional(),
    ShareSalesforceAction: z.enum(["DENY"]).optional(),
    UseSalesforceAction: z.enum(["DENY"]).optional(),
    MSExchangeAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateMSExchangeAction: z.enum(["DENY"]).optional(),
    ShareMSExchangeAction: z.enum(["DENY"]).optional(),
    UseMSExchangeAction: z.enum(["DENY"]).optional(),
    PagerDutyAction: z.enum(["DENY"]).optional(),
    CreateAndUpdatePagerDutyAction: z.enum(["DENY"]).optional(),
    SharePagerDutyAction: z.enum(["DENY"]).optional(),
    UsePagerDutyAction: z.enum(["DENY"]).optional(),
    JiraAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateJiraAction: z.enum(["DENY"]).optional(),
    ShareJiraAction: z.enum(["DENY"]).optional(),
    UseJiraAction: z.enum(["DENY"]).optional(),
    ConfluenceAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateConfluenceAction: z.enum(["DENY"]).optional(),
    ShareConfluenceAction: z.enum(["DENY"]).optional(),
    UseConfluenceAction: z.enum(["DENY"]).optional(),
    OneDriveAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateOneDriveAction: z.enum(["DENY"]).optional(),
    ShareOneDriveAction: z.enum(["DENY"]).optional(),
    UseOneDriveAction: z.enum(["DENY"]).optional(),
    SharePointAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSharePointAction: z.enum(["DENY"]).optional(),
    ShareSharePointAction: z.enum(["DENY"]).optional(),
    UseSharePointAction: z.enum(["DENY"]).optional(),
    MSTeamsAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateMSTeamsAction: z.enum(["DENY"]).optional(),
    ShareMSTeamsAction: z.enum(["DENY"]).optional(),
    UseMSTeamsAction: z.enum(["DENY"]).optional(),
    GoogleCalendarAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateGoogleCalendarAction: z.enum(["DENY"]).optional(),
    ShareGoogleCalendarAction: z.enum(["DENY"]).optional(),
    UseGoogleCalendarAction: z.enum(["DENY"]).optional(),
    ZendeskAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateZendeskAction: z.enum(["DENY"]).optional(),
    ShareZendeskAction: z.enum(["DENY"]).optional(),
    UseZendeskAction: z.enum(["DENY"]).optional(),
    SmartsheetAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSmartsheetAction: z.enum(["DENY"]).optional(),
    ShareSmartsheetAction: z.enum(["DENY"]).optional(),
    UseSmartsheetAction: z.enum(["DENY"]).optional(),
    SAPBusinessPartnerAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPBusinessPartnerAction: z.enum(["DENY"]).optional(),
    ShareSAPBusinessPartnerAction: z.enum(["DENY"]).optional(),
    UseSAPBusinessPartnerAction: z.enum(["DENY"]).optional(),
    SAPProductMasterDataAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPProductMasterDataAction: z.enum(["DENY"]).optional(),
    ShareSAPProductMasterDataAction: z.enum(["DENY"]).optional(),
    UseSAPProductMasterDataAction: z.enum(["DENY"]).optional(),
    SAPPhysicalInventoryAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPPhysicalInventoryAction: z.enum(["DENY"]).optional(),
    ShareSAPPhysicalInventoryAction: z.enum(["DENY"]).optional(),
    UseSAPPhysicalInventoryAction: z.enum(["DENY"]).optional(),
    SAPBillOfMaterialAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPBillOfMaterialAction: z.enum(["DENY"]).optional(),
    ShareSAPBillOfMaterialAction: z.enum(["DENY"]).optional(),
    UseSAPBillOfMaterialAction: z.enum(["DENY"]).optional(),
    SAPMaterialStockAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPMaterialStockAction: z.enum(["DENY"]).optional(),
    ShareSAPMaterialStockAction: z.enum(["DENY"]).optional(),
    UseSAPMaterialStockAction: z.enum(["DENY"]).optional(),
    FactSetAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateFactSetAction: z.enum(["DENY"]).optional(),
    ShareFactSetAction: z.enum(["DENY"]).optional(),
    UseFactSetAction: z.enum(["DENY"]).optional(),
    AmazonSThreeAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAmazonSThreeAction: z.enum(["DENY"]).optional(),
    ShareAmazonSThreeAction: z.enum(["DENY"]).optional(),
    UseAmazonSThreeAction: z.enum(["DENY"]).optional(),
    TextractAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateTextractAction: z.enum(["DENY"]).optional(),
    ShareTextractAction: z.enum(["DENY"]).optional(),
    UseTextractAction: z.enum(["DENY"]).optional(),
    ComprehendAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateComprehendAction: z.enum(["DENY"]).optional(),
    ShareComprehendAction: z.enum(["DENY"]).optional(),
    UseComprehendAction: z.enum(["DENY"]).optional(),
    ComprehendMedicalAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateComprehendMedicalAction: z.enum(["DENY"]).optional(),
    ShareComprehendMedicalAction: z.enum(["DENY"]).optional(),
    UseComprehendMedicalAction: z.enum(["DENY"]).optional(),
    AmazonBedrockARSAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAmazonBedrockARSAction: z.enum(["DENY"]).optional(),
    ShareAmazonBedrockARSAction: z.enum(["DENY"]).optional(),
    UseAmazonBedrockARSAction: z.enum(["DENY"]).optional(),
    AmazonBedrockFSAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAmazonBedrockFSAction: z.enum(["DENY"]).optional(),
    ShareAmazonBedrockFSAction: z.enum(["DENY"]).optional(),
    UseAmazonBedrockFSAction: z.enum(["DENY"]).optional(),
    AmazonBedrockKRSAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAmazonBedrockKRSAction: z.enum(["DENY"]).optional(),
    ShareAmazonBedrockKRSAction: z.enum(["DENY"]).optional(),
    UseAmazonBedrockKRSAction: z.enum(["DENY"]).optional(),
    MCPAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateMCPAction: z.enum(["DENY"]).optional(),
    ShareMCPAction: z.enum(["DENY"]).optional(),
    UseMCPAction: z.enum(["DENY"]).optional(),
    OpenAPIAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateOpenAPIAction: z.enum(["DENY"]).optional(),
    ShareOpenAPIAction: z.enum(["DENY"]).optional(),
    UseOpenAPIAction: z.enum(["DENY"]).optional(),
    SandPGMIAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSandPGMIAction: z.enum(["DENY"]).optional(),
    ShareSandPGMIAction: z.enum(["DENY"]).optional(),
    UseSandPGMIAction: z.enum(["DENY"]).optional(),
    SandPGlobalEnergyAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSandPGlobalEnergyAction: z.enum(["DENY"]).optional(),
    ShareSandPGlobalEnergyAction: z.enum(["DENY"]).optional(),
    UseSandPGlobalEnergyAction: z.enum(["DENY"]).optional(),
    BambooHRAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateBambooHRAction: z.enum(["DENY"]).optional(),
    ShareBambooHRAction: z.enum(["DENY"]).optional(),
    UseBambooHRAction: z.enum(["DENY"]).optional(),
    BoxAgentAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateBoxAgentAction: z.enum(["DENY"]).optional(),
    ShareBoxAgentAction: z.enum(["DENY"]).optional(),
    UseBoxAgentAction: z.enum(["DENY"]).optional(),
    CanvaAgentAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateCanvaAgentAction: z.enum(["DENY"]).optional(),
    ShareCanvaAgentAction: z.enum(["DENY"]).optional(),
    UseCanvaAgentAction: z.enum(["DENY"]).optional(),
    GithubAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateGithubAction: z.enum(["DENY"]).optional(),
    ShareGithubAction: z.enum(["DENY"]).optional(),
    UseGithubAction: z.enum(["DENY"]).optional(),
    NotionAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateNotionAction: z.enum(["DENY"]).optional(),
    ShareNotionAction: z.enum(["DENY"]).optional(),
    UseNotionAction: z.enum(["DENY"]).optional(),
    LinearAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateLinearAction: z.enum(["DENY"]).optional(),
    ShareLinearAction: z.enum(["DENY"]).optional(),
    UseLinearAction: z.enum(["DENY"]).optional(),
    HuggingFaceAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateHuggingFaceAction: z.enum(["DENY"]).optional(),
    ShareHuggingFaceAction: z.enum(["DENY"]).optional(),
    UseHuggingFaceAction: z.enum(["DENY"]).optional(),
    MondayAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateMondayAction: z.enum(["DENY"]).optional(),
    ShareMondayAction: z.enum(["DENY"]).optional(),
    UseMondayAction: z.enum(["DENY"]).optional(),
    HubspotAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateHubspotAction: z.enum(["DENY"]).optional(),
    ShareHubspotAction: z.enum(["DENY"]).optional(),
    UseHubspotAction: z.enum(["DENY"]).optional(),
    IntercomAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateIntercomAction: z.enum(["DENY"]).optional(),
    ShareIntercomAction: z.enum(["DENY"]).optional(),
    UseIntercomAction: z.enum(["DENY"]).optional(),
    NewRelicAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateNewRelicAction: z.enum(["DENY"]).optional(),
    ShareNewRelicAction: z.enum(["DENY"]).optional(),
    UseNewRelicAction: z.enum(["DENY"]).optional(),
    Space: z.enum(["DENY"]).optional(),
    ChatAgent: z.enum(["DENY"]).optional(),
    CreateChatAgents: z.enum(["DENY"]).optional(),
    Research: z.enum(["DENY"]).optional(),
    Extension: z.enum(["DENY"]).optional(),
    ManageSharedFolders: z.enum(["DENY"]).optional(),
    EditVisualWithQ: z.enum(["DENY"]).optional(),
    BuildCalculatedFieldWithQ: z.enum(["DENY"]).optional(),
    CreateDashboardExecutiveSummaryWithQ: z.enum(["DENY"]).optional(),
    Topic: z.enum(["DENY"]).optional(),
  }).optional(),
  CustomPermissionsName: z.string().min(1).max(64).regex(
    new RegExp("^[a-zA-Z0-9+=,.@_-]+$"),
  ),
  Tags: z.array(TagSchema).optional(),
});

const StateSchema = z.object({
  Arn: z.string().optional(),
  AwsAccountId: z.string(),
  Capabilities: z.object({
    ExportToCsv: z.string(),
    ExportToExcel: z.string(),
    ExportToPdf: z.string(),
    PrintReports: z.string(),
    CreateAndUpdateThemes: z.string(),
    AddOrRunAnomalyDetectionForAnalyses: z.string(),
    ShareAnalyses: z.string(),
    CreateAndUpdateDatasets: z.string(),
    ShareDatasets: z.string(),
    SubscribeDashboardEmailReports: z.string(),
    CreateAndUpdateDashboardEmailReports: z.string(),
    ShareDashboards: z.string(),
    CreateAndUpdateThresholdAlerts: z.string(),
    RenameSharedFolders: z.string(),
    CreateSharedFolders: z.string(),
    CreateAndUpdateDataSources: z.string(),
    ShareDataSources: z.string(),
    ViewAccountSPICECapacity: z.string(),
    CreateSPICEDataset: z.string(),
    ExportToPdfInScheduledReports: z.string(),
    ExportToCsvInScheduledReports: z.string(),
    ExportToExcelInScheduledReports: z.string(),
    IncludeContentInScheduledReportsEmail: z.string(),
    Dashboard: z.string(),
    Analysis: z.string(),
    Automate: z.string(),
    Flow: z.string(),
    PublishWithoutApproval: z.string(),
    UseBedrockModels: z.string(),
    PerformFlowUiTask: z.string(),
    ApproveFlowShareRequests: z.string(),
    UseAgentWebSearch: z.string(),
    KnowledgeBase: z.string(),
    CreateAndUpdateKnowledgeBases: z.string(),
    ShareKnowledgeBases: z.string(),
    Action: z.string(),
    GenericHTTPAction: z.string(),
    CreateAndUpdateGenericHTTPAction: z.string(),
    ShareGenericHTTPAction: z.string(),
    UseGenericHTTPAction: z.string(),
    AsanaAction: z.string(),
    CreateAndUpdateAsanaAction: z.string(),
    ShareAsanaAction: z.string(),
    UseAsanaAction: z.string(),
    SlackAction: z.string(),
    CreateAndUpdateSlackAction: z.string(),
    ShareSlackAction: z.string(),
    UseSlackAction: z.string(),
    ServiceNowAction: z.string(),
    CreateAndUpdateServiceNowAction: z.string(),
    ShareServiceNowAction: z.string(),
    UseServiceNowAction: z.string(),
    SalesforceAction: z.string(),
    CreateAndUpdateSalesforceAction: z.string(),
    ShareSalesforceAction: z.string(),
    UseSalesforceAction: z.string(),
    MSExchangeAction: z.string(),
    CreateAndUpdateMSExchangeAction: z.string(),
    ShareMSExchangeAction: z.string(),
    UseMSExchangeAction: z.string(),
    PagerDutyAction: z.string(),
    CreateAndUpdatePagerDutyAction: z.string(),
    SharePagerDutyAction: z.string(),
    UsePagerDutyAction: z.string(),
    JiraAction: z.string(),
    CreateAndUpdateJiraAction: z.string(),
    ShareJiraAction: z.string(),
    UseJiraAction: z.string(),
    ConfluenceAction: z.string(),
    CreateAndUpdateConfluenceAction: z.string(),
    ShareConfluenceAction: z.string(),
    UseConfluenceAction: z.string(),
    OneDriveAction: z.string(),
    CreateAndUpdateOneDriveAction: z.string(),
    ShareOneDriveAction: z.string(),
    UseOneDriveAction: z.string(),
    SharePointAction: z.string(),
    CreateAndUpdateSharePointAction: z.string(),
    ShareSharePointAction: z.string(),
    UseSharePointAction: z.string(),
    MSTeamsAction: z.string(),
    CreateAndUpdateMSTeamsAction: z.string(),
    ShareMSTeamsAction: z.string(),
    UseMSTeamsAction: z.string(),
    GoogleCalendarAction: z.string(),
    CreateAndUpdateGoogleCalendarAction: z.string(),
    ShareGoogleCalendarAction: z.string(),
    UseGoogleCalendarAction: z.string(),
    ZendeskAction: z.string(),
    CreateAndUpdateZendeskAction: z.string(),
    ShareZendeskAction: z.string(),
    UseZendeskAction: z.string(),
    SmartsheetAction: z.string(),
    CreateAndUpdateSmartsheetAction: z.string(),
    ShareSmartsheetAction: z.string(),
    UseSmartsheetAction: z.string(),
    SAPBusinessPartnerAction: z.string(),
    CreateAndUpdateSAPBusinessPartnerAction: z.string(),
    ShareSAPBusinessPartnerAction: z.string(),
    UseSAPBusinessPartnerAction: z.string(),
    SAPProductMasterDataAction: z.string(),
    CreateAndUpdateSAPProductMasterDataAction: z.string(),
    ShareSAPProductMasterDataAction: z.string(),
    UseSAPProductMasterDataAction: z.string(),
    SAPPhysicalInventoryAction: z.string(),
    CreateAndUpdateSAPPhysicalInventoryAction: z.string(),
    ShareSAPPhysicalInventoryAction: z.string(),
    UseSAPPhysicalInventoryAction: z.string(),
    SAPBillOfMaterialAction: z.string(),
    CreateAndUpdateSAPBillOfMaterialAction: z.string(),
    ShareSAPBillOfMaterialAction: z.string(),
    UseSAPBillOfMaterialAction: z.string(),
    SAPMaterialStockAction: z.string(),
    CreateAndUpdateSAPMaterialStockAction: z.string(),
    ShareSAPMaterialStockAction: z.string(),
    UseSAPMaterialStockAction: z.string(),
    FactSetAction: z.string(),
    CreateAndUpdateFactSetAction: z.string(),
    ShareFactSetAction: z.string(),
    UseFactSetAction: z.string(),
    AmazonSThreeAction: z.string(),
    CreateAndUpdateAmazonSThreeAction: z.string(),
    ShareAmazonSThreeAction: z.string(),
    UseAmazonSThreeAction: z.string(),
    TextractAction: z.string(),
    CreateAndUpdateTextractAction: z.string(),
    ShareTextractAction: z.string(),
    UseTextractAction: z.string(),
    ComprehendAction: z.string(),
    CreateAndUpdateComprehendAction: z.string(),
    ShareComprehendAction: z.string(),
    UseComprehendAction: z.string(),
    ComprehendMedicalAction: z.string(),
    CreateAndUpdateComprehendMedicalAction: z.string(),
    ShareComprehendMedicalAction: z.string(),
    UseComprehendMedicalAction: z.string(),
    AmazonBedrockARSAction: z.string(),
    CreateAndUpdateAmazonBedrockARSAction: z.string(),
    ShareAmazonBedrockARSAction: z.string(),
    UseAmazonBedrockARSAction: z.string(),
    AmazonBedrockFSAction: z.string(),
    CreateAndUpdateAmazonBedrockFSAction: z.string(),
    ShareAmazonBedrockFSAction: z.string(),
    UseAmazonBedrockFSAction: z.string(),
    AmazonBedrockKRSAction: z.string(),
    CreateAndUpdateAmazonBedrockKRSAction: z.string(),
    ShareAmazonBedrockKRSAction: z.string(),
    UseAmazonBedrockKRSAction: z.string(),
    MCPAction: z.string(),
    CreateAndUpdateMCPAction: z.string(),
    ShareMCPAction: z.string(),
    UseMCPAction: z.string(),
    OpenAPIAction: z.string(),
    CreateAndUpdateOpenAPIAction: z.string(),
    ShareOpenAPIAction: z.string(),
    UseOpenAPIAction: z.string(),
    SandPGMIAction: z.string(),
    CreateAndUpdateSandPGMIAction: z.string(),
    ShareSandPGMIAction: z.string(),
    UseSandPGMIAction: z.string(),
    SandPGlobalEnergyAction: z.string(),
    CreateAndUpdateSandPGlobalEnergyAction: z.string(),
    ShareSandPGlobalEnergyAction: z.string(),
    UseSandPGlobalEnergyAction: z.string(),
    BambooHRAction: z.string(),
    CreateAndUpdateBambooHRAction: z.string(),
    ShareBambooHRAction: z.string(),
    UseBambooHRAction: z.string(),
    BoxAgentAction: z.string(),
    CreateAndUpdateBoxAgentAction: z.string(),
    ShareBoxAgentAction: z.string(),
    UseBoxAgentAction: z.string(),
    CanvaAgentAction: z.string(),
    CreateAndUpdateCanvaAgentAction: z.string(),
    ShareCanvaAgentAction: z.string(),
    UseCanvaAgentAction: z.string(),
    GithubAction: z.string(),
    CreateAndUpdateGithubAction: z.string(),
    ShareGithubAction: z.string(),
    UseGithubAction: z.string(),
    NotionAction: z.string(),
    CreateAndUpdateNotionAction: z.string(),
    ShareNotionAction: z.string(),
    UseNotionAction: z.string(),
    LinearAction: z.string(),
    CreateAndUpdateLinearAction: z.string(),
    ShareLinearAction: z.string(),
    UseLinearAction: z.string(),
    HuggingFaceAction: z.string(),
    CreateAndUpdateHuggingFaceAction: z.string(),
    ShareHuggingFaceAction: z.string(),
    UseHuggingFaceAction: z.string(),
    MondayAction: z.string(),
    CreateAndUpdateMondayAction: z.string(),
    ShareMondayAction: z.string(),
    UseMondayAction: z.string(),
    HubspotAction: z.string(),
    CreateAndUpdateHubspotAction: z.string(),
    ShareHubspotAction: z.string(),
    UseHubspotAction: z.string(),
    IntercomAction: z.string(),
    CreateAndUpdateIntercomAction: z.string(),
    ShareIntercomAction: z.string(),
    UseIntercomAction: z.string(),
    NewRelicAction: z.string(),
    CreateAndUpdateNewRelicAction: z.string(),
    ShareNewRelicAction: z.string(),
    UseNewRelicAction: z.string(),
    Space: z.string(),
    ChatAgent: z.string(),
    CreateChatAgents: z.string(),
    Research: z.string(),
    Extension: z.string(),
    ManageSharedFolders: z.string(),
    EditVisualWithQ: z.string(),
    BuildCalculatedFieldWithQ: z.string(),
    CreateDashboardExecutiveSummaryWithQ: z.string(),
    Topic: z.string(),
  }).optional(),
  CustomPermissionsName: z.string(),
  Tags: z.array(TagSchema).optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  name: z.string().optional(),
  AwsAccountId: z.string().min(12).max(12).regex(new RegExp("^[0-9]{12}$"))
    .optional(),
  Capabilities: z.object({
    ExportToCsv: z.enum(["DENY"]).optional(),
    ExportToExcel: z.enum(["DENY"]).optional(),
    ExportToPdf: z.enum(["DENY"]).optional(),
    PrintReports: z.enum(["DENY"]).optional(),
    CreateAndUpdateThemes: z.enum(["DENY"]).optional(),
    AddOrRunAnomalyDetectionForAnalyses: z.enum(["DENY"]).optional(),
    ShareAnalyses: z.enum(["DENY"]).optional(),
    CreateAndUpdateDatasets: z.enum(["DENY"]).optional(),
    ShareDatasets: z.enum(["DENY"]).optional(),
    SubscribeDashboardEmailReports: z.enum(["DENY"]).optional(),
    CreateAndUpdateDashboardEmailReports: z.enum(["DENY"]).optional(),
    ShareDashboards: z.enum(["DENY"]).optional(),
    CreateAndUpdateThresholdAlerts: z.enum(["DENY"]).optional(),
    RenameSharedFolders: z.enum(["DENY"]).optional(),
    CreateSharedFolders: z.enum(["DENY"]).optional(),
    CreateAndUpdateDataSources: z.enum(["DENY"]).optional(),
    ShareDataSources: z.enum(["DENY"]).optional(),
    ViewAccountSPICECapacity: z.enum(["DENY"]).optional(),
    CreateSPICEDataset: z.enum(["DENY"]).optional(),
    ExportToPdfInScheduledReports: z.enum(["DENY"]).optional(),
    ExportToCsvInScheduledReports: z.enum(["DENY"]).optional(),
    ExportToExcelInScheduledReports: z.enum(["DENY"]).optional(),
    IncludeContentInScheduledReportsEmail: z.enum(["DENY"]).optional(),
    Dashboard: z.enum(["DENY"]).optional(),
    Analysis: z.enum(["DENY"]).optional(),
    Automate: z.enum(["DENY"]).optional(),
    Flow: z.enum(["DENY"]).optional(),
    PublishWithoutApproval: z.enum(["DENY"]).optional(),
    UseBedrockModels: z.enum(["DENY"]).optional(),
    PerformFlowUiTask: z.enum(["DENY"]).optional(),
    ApproveFlowShareRequests: z.enum(["DENY"]).optional(),
    UseAgentWebSearch: z.enum(["DENY"]).optional(),
    KnowledgeBase: z.enum(["DENY"]).optional(),
    CreateAndUpdateKnowledgeBases: z.enum(["DENY"]).optional(),
    ShareKnowledgeBases: z.enum(["DENY"]).optional(),
    Action: z.enum(["DENY"]).optional(),
    GenericHTTPAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateGenericHTTPAction: z.enum(["DENY"]).optional(),
    ShareGenericHTTPAction: z.enum(["DENY"]).optional(),
    UseGenericHTTPAction: z.enum(["DENY"]).optional(),
    AsanaAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAsanaAction: z.enum(["DENY"]).optional(),
    ShareAsanaAction: z.enum(["DENY"]).optional(),
    UseAsanaAction: z.enum(["DENY"]).optional(),
    SlackAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSlackAction: z.enum(["DENY"]).optional(),
    ShareSlackAction: z.enum(["DENY"]).optional(),
    UseSlackAction: z.enum(["DENY"]).optional(),
    ServiceNowAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateServiceNowAction: z.enum(["DENY"]).optional(),
    ShareServiceNowAction: z.enum(["DENY"]).optional(),
    UseServiceNowAction: z.enum(["DENY"]).optional(),
    SalesforceAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSalesforceAction: z.enum(["DENY"]).optional(),
    ShareSalesforceAction: z.enum(["DENY"]).optional(),
    UseSalesforceAction: z.enum(["DENY"]).optional(),
    MSExchangeAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateMSExchangeAction: z.enum(["DENY"]).optional(),
    ShareMSExchangeAction: z.enum(["DENY"]).optional(),
    UseMSExchangeAction: z.enum(["DENY"]).optional(),
    PagerDutyAction: z.enum(["DENY"]).optional(),
    CreateAndUpdatePagerDutyAction: z.enum(["DENY"]).optional(),
    SharePagerDutyAction: z.enum(["DENY"]).optional(),
    UsePagerDutyAction: z.enum(["DENY"]).optional(),
    JiraAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateJiraAction: z.enum(["DENY"]).optional(),
    ShareJiraAction: z.enum(["DENY"]).optional(),
    UseJiraAction: z.enum(["DENY"]).optional(),
    ConfluenceAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateConfluenceAction: z.enum(["DENY"]).optional(),
    ShareConfluenceAction: z.enum(["DENY"]).optional(),
    UseConfluenceAction: z.enum(["DENY"]).optional(),
    OneDriveAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateOneDriveAction: z.enum(["DENY"]).optional(),
    ShareOneDriveAction: z.enum(["DENY"]).optional(),
    UseOneDriveAction: z.enum(["DENY"]).optional(),
    SharePointAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSharePointAction: z.enum(["DENY"]).optional(),
    ShareSharePointAction: z.enum(["DENY"]).optional(),
    UseSharePointAction: z.enum(["DENY"]).optional(),
    MSTeamsAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateMSTeamsAction: z.enum(["DENY"]).optional(),
    ShareMSTeamsAction: z.enum(["DENY"]).optional(),
    UseMSTeamsAction: z.enum(["DENY"]).optional(),
    GoogleCalendarAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateGoogleCalendarAction: z.enum(["DENY"]).optional(),
    ShareGoogleCalendarAction: z.enum(["DENY"]).optional(),
    UseGoogleCalendarAction: z.enum(["DENY"]).optional(),
    ZendeskAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateZendeskAction: z.enum(["DENY"]).optional(),
    ShareZendeskAction: z.enum(["DENY"]).optional(),
    UseZendeskAction: z.enum(["DENY"]).optional(),
    SmartsheetAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSmartsheetAction: z.enum(["DENY"]).optional(),
    ShareSmartsheetAction: z.enum(["DENY"]).optional(),
    UseSmartsheetAction: z.enum(["DENY"]).optional(),
    SAPBusinessPartnerAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPBusinessPartnerAction: z.enum(["DENY"]).optional(),
    ShareSAPBusinessPartnerAction: z.enum(["DENY"]).optional(),
    UseSAPBusinessPartnerAction: z.enum(["DENY"]).optional(),
    SAPProductMasterDataAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPProductMasterDataAction: z.enum(["DENY"]).optional(),
    ShareSAPProductMasterDataAction: z.enum(["DENY"]).optional(),
    UseSAPProductMasterDataAction: z.enum(["DENY"]).optional(),
    SAPPhysicalInventoryAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPPhysicalInventoryAction: z.enum(["DENY"]).optional(),
    ShareSAPPhysicalInventoryAction: z.enum(["DENY"]).optional(),
    UseSAPPhysicalInventoryAction: z.enum(["DENY"]).optional(),
    SAPBillOfMaterialAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPBillOfMaterialAction: z.enum(["DENY"]).optional(),
    ShareSAPBillOfMaterialAction: z.enum(["DENY"]).optional(),
    UseSAPBillOfMaterialAction: z.enum(["DENY"]).optional(),
    SAPMaterialStockAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSAPMaterialStockAction: z.enum(["DENY"]).optional(),
    ShareSAPMaterialStockAction: z.enum(["DENY"]).optional(),
    UseSAPMaterialStockAction: z.enum(["DENY"]).optional(),
    FactSetAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateFactSetAction: z.enum(["DENY"]).optional(),
    ShareFactSetAction: z.enum(["DENY"]).optional(),
    UseFactSetAction: z.enum(["DENY"]).optional(),
    AmazonSThreeAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAmazonSThreeAction: z.enum(["DENY"]).optional(),
    ShareAmazonSThreeAction: z.enum(["DENY"]).optional(),
    UseAmazonSThreeAction: z.enum(["DENY"]).optional(),
    TextractAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateTextractAction: z.enum(["DENY"]).optional(),
    ShareTextractAction: z.enum(["DENY"]).optional(),
    UseTextractAction: z.enum(["DENY"]).optional(),
    ComprehendAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateComprehendAction: z.enum(["DENY"]).optional(),
    ShareComprehendAction: z.enum(["DENY"]).optional(),
    UseComprehendAction: z.enum(["DENY"]).optional(),
    ComprehendMedicalAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateComprehendMedicalAction: z.enum(["DENY"]).optional(),
    ShareComprehendMedicalAction: z.enum(["DENY"]).optional(),
    UseComprehendMedicalAction: z.enum(["DENY"]).optional(),
    AmazonBedrockARSAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAmazonBedrockARSAction: z.enum(["DENY"]).optional(),
    ShareAmazonBedrockARSAction: z.enum(["DENY"]).optional(),
    UseAmazonBedrockARSAction: z.enum(["DENY"]).optional(),
    AmazonBedrockFSAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAmazonBedrockFSAction: z.enum(["DENY"]).optional(),
    ShareAmazonBedrockFSAction: z.enum(["DENY"]).optional(),
    UseAmazonBedrockFSAction: z.enum(["DENY"]).optional(),
    AmazonBedrockKRSAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateAmazonBedrockKRSAction: z.enum(["DENY"]).optional(),
    ShareAmazonBedrockKRSAction: z.enum(["DENY"]).optional(),
    UseAmazonBedrockKRSAction: z.enum(["DENY"]).optional(),
    MCPAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateMCPAction: z.enum(["DENY"]).optional(),
    ShareMCPAction: z.enum(["DENY"]).optional(),
    UseMCPAction: z.enum(["DENY"]).optional(),
    OpenAPIAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateOpenAPIAction: z.enum(["DENY"]).optional(),
    ShareOpenAPIAction: z.enum(["DENY"]).optional(),
    UseOpenAPIAction: z.enum(["DENY"]).optional(),
    SandPGMIAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSandPGMIAction: z.enum(["DENY"]).optional(),
    ShareSandPGMIAction: z.enum(["DENY"]).optional(),
    UseSandPGMIAction: z.enum(["DENY"]).optional(),
    SandPGlobalEnergyAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateSandPGlobalEnergyAction: z.enum(["DENY"]).optional(),
    ShareSandPGlobalEnergyAction: z.enum(["DENY"]).optional(),
    UseSandPGlobalEnergyAction: z.enum(["DENY"]).optional(),
    BambooHRAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateBambooHRAction: z.enum(["DENY"]).optional(),
    ShareBambooHRAction: z.enum(["DENY"]).optional(),
    UseBambooHRAction: z.enum(["DENY"]).optional(),
    BoxAgentAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateBoxAgentAction: z.enum(["DENY"]).optional(),
    ShareBoxAgentAction: z.enum(["DENY"]).optional(),
    UseBoxAgentAction: z.enum(["DENY"]).optional(),
    CanvaAgentAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateCanvaAgentAction: z.enum(["DENY"]).optional(),
    ShareCanvaAgentAction: z.enum(["DENY"]).optional(),
    UseCanvaAgentAction: z.enum(["DENY"]).optional(),
    GithubAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateGithubAction: z.enum(["DENY"]).optional(),
    ShareGithubAction: z.enum(["DENY"]).optional(),
    UseGithubAction: z.enum(["DENY"]).optional(),
    NotionAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateNotionAction: z.enum(["DENY"]).optional(),
    ShareNotionAction: z.enum(["DENY"]).optional(),
    UseNotionAction: z.enum(["DENY"]).optional(),
    LinearAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateLinearAction: z.enum(["DENY"]).optional(),
    ShareLinearAction: z.enum(["DENY"]).optional(),
    UseLinearAction: z.enum(["DENY"]).optional(),
    HuggingFaceAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateHuggingFaceAction: z.enum(["DENY"]).optional(),
    ShareHuggingFaceAction: z.enum(["DENY"]).optional(),
    UseHuggingFaceAction: z.enum(["DENY"]).optional(),
    MondayAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateMondayAction: z.enum(["DENY"]).optional(),
    ShareMondayAction: z.enum(["DENY"]).optional(),
    UseMondayAction: z.enum(["DENY"]).optional(),
    HubspotAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateHubspotAction: z.enum(["DENY"]).optional(),
    ShareHubspotAction: z.enum(["DENY"]).optional(),
    UseHubspotAction: z.enum(["DENY"]).optional(),
    IntercomAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateIntercomAction: z.enum(["DENY"]).optional(),
    ShareIntercomAction: z.enum(["DENY"]).optional(),
    UseIntercomAction: z.enum(["DENY"]).optional(),
    NewRelicAction: z.enum(["DENY"]).optional(),
    CreateAndUpdateNewRelicAction: z.enum(["DENY"]).optional(),
    ShareNewRelicAction: z.enum(["DENY"]).optional(),
    UseNewRelicAction: z.enum(["DENY"]).optional(),
    Space: z.enum(["DENY"]).optional(),
    ChatAgent: z.enum(["DENY"]).optional(),
    CreateChatAgents: z.enum(["DENY"]).optional(),
    Research: z.enum(["DENY"]).optional(),
    Extension: z.enum(["DENY"]).optional(),
    ManageSharedFolders: z.enum(["DENY"]).optional(),
    EditVisualWithQ: z.enum(["DENY"]).optional(),
    BuildCalculatedFieldWithQ: z.enum(["DENY"]).optional(),
    CreateDashboardExecutiveSummaryWithQ: z.enum(["DENY"]).optional(),
    Topic: z.enum(["DENY"]).optional(),
  }).optional(),
  CustomPermissionsName: z.string().min(1).max(64).regex(
    new RegExp("^[a-zA-Z0-9+=,.@_-]+$"),
  ).optional(),
  Tags: z.array(TagSchema).optional(),
});

export const model = {
  type: "@swamp/aws/quicksight/custom-permissions",
  version: "2026.04.03.2",
  upgrades: [
    {
      toVersion: "2026.04.01.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description: "QuickSight CustomPermissions resource state",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a QuickSight CustomPermissions",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const desiredState: Record<string, unknown> = {};
        for (const [key, value] of Object.entries(g)) {
          if (key === "name") continue;
          if (value !== undefined) desiredState[key] = value;
        }
        const result = await createResource(
          "AWS::QuickSight::CustomPermissions",
          desiredState,
        ) as StateData;
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a QuickSight CustomPermissions",
      arguments: z.object({
        identifier: z.string().describe(
          "The primary identifier of the QuickSight CustomPermissions",
        ),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const result = await readResource(
          "AWS::QuickSight::CustomPermissions",
          args.identifier,
        ) as StateData;
        const instanceName =
          (context.globalArgs.name?.toString() ?? args.identifier).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update a QuickSight CustomPermissions",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const idParts = [
          existing.AwsAccountId?.toString(),
          existing.CustomPermissionsName?.toString(),
        ];
        if (idParts.some((p) => !p)) {
          throw new Error(
            "Missing primary identifier fields in existing state",
          );
        }
        const identifier = idParts.join("|");
        const currentState = await readResource(
          "AWS::QuickSight::CustomPermissions",
          identifier,
        ) as StateData;
        const desiredState: Record<string, unknown> = { ...currentState };
        for (const [key, value] of Object.entries(g)) {
          if (key === "name") continue;
          if (value !== undefined) desiredState[key] = value;
        }
        const result = await updateResource(
          "AWS::QuickSight::CustomPermissions",
          identifier,
          currentState,
          desiredState,
          ["AwsAccountId", "CustomPermissionsName"],
        );
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete a QuickSight CustomPermissions",
      arguments: z.object({
        identifier: z.string().describe(
          "The primary identifier of the QuickSight CustomPermissions",
        ),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const { existed } = await deleteResource(
          "AWS::QuickSight::CustomPermissions",
          args.identifier,
        );
        const instanceName =
          (context.globalArgs.name?.toString() ?? args.identifier).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync QuickSight CustomPermissions state from AWS",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const idParts = [
          existing.AwsAccountId?.toString(),
          existing.CustomPermissionsName?.toString(),
        ];
        if (idParts.some((p) => !p)) {
          throw new Error(
            "Missing primary identifier fields in existing state",
          );
        }
        const identifier = idParts.join("|");
        try {
          const result = await readResource(
            "AWS::QuickSight::CustomPermissions",
            identifier,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              identifier,
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
  },
};
