// Auto-generated extension model for @swamp/gcp/youtubeAnalytics/groups
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

import { z } from "zod";
import {
  createResource,
  deleteResource,
  getProjectId,
  isResourceNotFoundError,
  readViaList,
  updateResource,
} from "./_lib/gcp.ts";

const BASE_URL = "https://youtubeanalytics.googleapis.com/";

const INSERT_CONFIG = {
  "id": "youtubeAnalytics.groups.insert",
  "path": "v2/groups",
  "httpMethod": "POST",
  "parameterOrder": [],
  "parameters": {
    "onBehalfOfContentOwner": {
      "location": "query",
    },
  },
} as const;

const UPDATE_CONFIG = {
  "id": "youtubeAnalytics.groups.update",
  "path": "v2/groups",
  "httpMethod": "PUT",
  "parameterOrder": [],
  "parameters": {
    "onBehalfOfContentOwner": {
      "location": "query",
    },
  },
} as const;

const DELETE_CONFIG = {
  "id": "youtubeAnalytics.groups.delete",
  "path": "v2/groups",
  "httpMethod": "DELETE",
  "parameterOrder": [],
  "parameters": {
    "id": {
      "location": "query",
    },
    "onBehalfOfContentOwner": {
      "location": "query",
    },
  },
} as const;

const LIST_CONFIG = {
  "id": "youtubeAnalytics.groups.list",
  "path": "v2/groups",
  "httpMethod": "GET",
  "parameterOrder": [],
  "parameters": {
    "id": {
      "location": "query",
    },
    "mine": {
      "location": "query",
    },
    "onBehalfOfContentOwner": {
      "location": "query",
    },
    "pageToken": {
      "location": "query",
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  name: z.string().describe(
    "Instance name for this resource (used as the unique identifier in the factory pattern)",
  ),
  contentDetails: z.object({
    itemCount: z.string().describe("The number of items in the group.")
      .optional(),
    itemType: z.string().describe(
      "The type of resources that the group contains. Valid values for this property are: * `youtube#channel` * `youtube#playlist` * `youtube#video` * `youtubePartner#asset`",
    ).optional(),
  }).describe("A group's content details.").optional(),
  errors: z.object({
    code: z.enum([
      "BAD_REQUEST",
      "FORBIDDEN",
      "NOT_FOUND",
      "CONFLICT",
      "GONE",
      "PRECONDITION_FAILED",
      "INTERNAL_ERROR",
      "SERVICE_UNAVAILABLE",
    ]).describe(
      "Global error code. Deprecated and ignored. Set custom error codes in ErrorProto.domain and ErrorProto.code instead.",
    ).optional(),
    error: z.array(z.object({
      argument: z.array(z.string()).describe(
        "Error arguments, to be used when building user-friendly error messages given the error domain and code. Different error codes require different arguments.",
      ).optional(),
      code: z.string().describe(
        "Error code in the error domain. This should correspond to a value of the enum type whose name is in domain. See the core error domain in error_domain.proto.",
      ).optional(),
      debugInfo: z.string().describe(
        "Debugging information, which should not be shared externally.",
      ).optional(),
      domain: z.string().describe(
        "Error domain. RoSy services can define their own domain and error codes. This should normally be the name of an enum type, such as: gdata.CoreErrorDomain",
      ).optional(),
      externalErrorMessage: z.string().describe(
        "A short explanation for the error, which can be shared outside Google. Please set domain, code and arguments whenever possible instead of this error message so that external APIs can build safe error messages themselves. External messages built in a RoSy interface will most likely refer to information and concepts that are not available externally and should not be exposed. It is safer if external APIs can understand the errors and decide what the error message should look like.",
      ).optional(),
      location: z.string().describe(
        "Location of the error, as specified by the location type. If location_type is PATH, this should be a path to a field that's relative to the request, using FieldPath notation (net/proto2/util/public/field_path.h). Examples: authenticated_user.gaia_id resource.address[2].country",
      ).optional(),
      locationType: z.enum(["PATH", "OTHER", "PARAMETER"]).optional(),
    })).describe("Specific error description and codes").optional(),
    requestId: z.string().describe(
      "Request identifier generated by the service, which can be used to identify the error in the logs",
    ).optional(),
  }).describe(
    "Request Error information. The presence of an error field signals that the operation has failed.",
  ).optional(),
  id: z.string().describe(
    "The ID that YouTube uses to uniquely identify the group.",
  ).optional(),
  snippet: z.object({
    publishedAt: z.string().describe(
      "The date and time that the group was created. The value is specified in ISO 8601 (YYYY-MM-DDThh:mm:ss.sZ) format.",
    ).optional(),
    title: z.string().describe(
      "The group name. The value must be a non-empty string.",
    ).optional(),
  }).describe("A group snippet.").optional(),
  onBehalfOfContentOwner: z.string().describe(
    "This parameter can only be used in a properly authorized request. **Note:** This parameter is intended exclusively for YouTube content partners that own and manage many different YouTube channels. The `onBehalfOfContentOwner` parameter indicates that the request's authorization credentials identify a YouTube user who is acting on behalf of the content owner specified in the parameter value. It allows content owners to authenticate once and get access to all their video and channel data, without having to provide authentication credentials for each individual channel. The account that the user authenticates with must be linked to the specified YouTube content owner.",
  ).optional(),
});

const StateSchema = z.object({
  contentDetails: z.object({
    itemCount: z.string(),
    itemType: z.string(),
  }).optional(),
  errors: z.object({
    code: z.string(),
    error: z.array(z.object({
      argument: z.array(z.string()),
      code: z.string(),
      debugInfo: z.string(),
      domain: z.string(),
      externalErrorMessage: z.string(),
      location: z.string(),
      locationType: z.string(),
    })),
    requestId: z.string(),
  }).optional(),
  etag: z.string().optional(),
  id: z.string().optional(),
  kind: z.string().optional(),
  snippet: z.object({
    publishedAt: z.string(),
    title: z.string(),
  }).optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  name: z.string().optional(),
  contentDetails: z.object({
    itemCount: z.string().describe("The number of items in the group.")
      .optional(),
    itemType: z.string().describe(
      "The type of resources that the group contains. Valid values for this property are: * `youtube#channel` * `youtube#playlist` * `youtube#video` * `youtubePartner#asset`",
    ).optional(),
  }).describe("A group's content details.").optional(),
  errors: z.object({
    code: z.enum([
      "BAD_REQUEST",
      "FORBIDDEN",
      "NOT_FOUND",
      "CONFLICT",
      "GONE",
      "PRECONDITION_FAILED",
      "INTERNAL_ERROR",
      "SERVICE_UNAVAILABLE",
    ]).describe(
      "Global error code. Deprecated and ignored. Set custom error codes in ErrorProto.domain and ErrorProto.code instead.",
    ).optional(),
    error: z.array(z.object({
      argument: z.array(z.string()).describe(
        "Error arguments, to be used when building user-friendly error messages given the error domain and code. Different error codes require different arguments.",
      ).optional(),
      code: z.string().describe(
        "Error code in the error domain. This should correspond to a value of the enum type whose name is in domain. See the core error domain in error_domain.proto.",
      ).optional(),
      debugInfo: z.string().describe(
        "Debugging information, which should not be shared externally.",
      ).optional(),
      domain: z.string().describe(
        "Error domain. RoSy services can define their own domain and error codes. This should normally be the name of an enum type, such as: gdata.CoreErrorDomain",
      ).optional(),
      externalErrorMessage: z.string().describe(
        "A short explanation for the error, which can be shared outside Google. Please set domain, code and arguments whenever possible instead of this error message so that external APIs can build safe error messages themselves. External messages built in a RoSy interface will most likely refer to information and concepts that are not available externally and should not be exposed. It is safer if external APIs can understand the errors and decide what the error message should look like.",
      ).optional(),
      location: z.string().describe(
        "Location of the error, as specified by the location type. If location_type is PATH, this should be a path to a field that's relative to the request, using FieldPath notation (net/proto2/util/public/field_path.h). Examples: authenticated_user.gaia_id resource.address[2].country",
      ).optional(),
      locationType: z.enum(["PATH", "OTHER", "PARAMETER"]).optional(),
    })).describe("Specific error description and codes").optional(),
    requestId: z.string().describe(
      "Request identifier generated by the service, which can be used to identify the error in the logs",
    ).optional(),
  }).describe(
    "Request Error information. The presence of an error field signals that the operation has failed.",
  ).optional(),
  id: z.string().describe(
    "The ID that YouTube uses to uniquely identify the group.",
  ).optional(),
  snippet: z.object({
    publishedAt: z.string().describe(
      "The date and time that the group was created. The value is specified in ISO 8601 (YYYY-MM-DDThh:mm:ss.sZ) format.",
    ).optional(),
    title: z.string().describe(
      "The group name. The value must be a non-empty string.",
    ).optional(),
  }).describe("A group snippet.").optional(),
  onBehalfOfContentOwner: z.string().describe(
    "This parameter can only be used in a properly authorized request. **Note:** This parameter is intended exclusively for YouTube content partners that own and manage many different YouTube channels. The `onBehalfOfContentOwner` parameter indicates that the request's authorization credentials identify a YouTube user who is acting on behalf of the content owner specified in the parameter value. It allows content owners to authenticate once and get access to all their video and channel data, without having to provide authentication credentials for each individual channel. The account that the user authenticates with must be linked to the specified YouTube content owner.",
  ).optional(),
});

export const model = {
  type: "@swamp/gcp/youtubeAnalytics/groups",
  version: "2026.03.27.1",
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description: "A group.",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a groups",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const body: Record<string, unknown> = {};
        if (g["contentDetails"] !== undefined) {
          body["contentDetails"] = g["contentDetails"];
        }
        if (g["errors"] !== undefined) body["errors"] = g["errors"];
        if (g["id"] !== undefined) body["id"] = g["id"];
        if (g["snippet"] !== undefined) body["snippet"] = g["snippet"];
        if (g["onBehalfOfContentOwner"] !== undefined) {
          body["onBehalfOfContentOwner"] = g["onBehalfOfContentOwner"];
        }
        const result = await createResource(
          BASE_URL,
          INSERT_CONFIG,
          params,
          body,
        ) as StateData;
        const instanceName = g.name?.toString() ?? "current";
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a groups",
      arguments: z.object({
        identifier: z.string().describe("The name of the groups"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const g = context.globalArgs;
        const result = await readViaList(
          BASE_URL,
          LIST_CONFIG,
          params,
          "name",
          args.identifier,
        ) as StateData;
        const instanceName = g.name?.toString() ?? args.identifier;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update groups attributes",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const params: Record<string, string> = { project: projectId };
        const body: Record<string, unknown> = {};
        if (g["contentDetails"] !== undefined) {
          body["contentDetails"] = g["contentDetails"];
        }
        if (g["errors"] !== undefined) body["errors"] = g["errors"];
        if (g["id"] !== undefined) body["id"] = g["id"];
        if (g["snippet"] !== undefined) body["snippet"] = g["snippet"];
        const result = await updateResource(
          BASE_URL,
          UPDATE_CONFIG,
          params,
          body,
        ) as StateData;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete the groups",
      arguments: z.object({
        identifier: z.string().describe("The name of the groups"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const { existed } = await deleteResource(
          BASE_URL,
          DELETE_CONFIG,
          params,
        );
        const instanceName = g.name?.toString() ?? args.identifier;
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync groups state from GCP",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = g.name?.toString() ?? "current";
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { project: projectId };
          const identifier = existing.name?.toString() ?? g["name"]?.toString();
          if (!identifier) {
            throw new Error(
              "No identifier found in existing state or globalArgs",
            );
          }
          const result = await readViaList(
            BASE_URL,
            LIST_CONFIG,
            params,
            "name",
            identifier,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
  },
};
